const express = require('express');
const router = express.Router();
const departmentController = require('./departments.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createDepartment, updateDepartment } = require('./departments.validation');

// Module name for routes-tree grouping
router.moduleName = 'Departments';

router.use(verifyToken);
router.use(moduleCheck('departments'));

// Define routes metadata
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => departmentController.getDepartments(req, res),
        description: 'List all departments',
        database: {
            tables: ['departments', 'staffs'],
            mainTable: 'departments',
            fields: {
                departments: ['id', 'name', 'description', 'head_id', 'status', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name']
            },
            relationships: ['departments.head_id -> staffs.id (FK)']
        },
        queryParams: {
            status: 'Filter by status',
            search: 'Search by name or description',
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Departments retrieved successfully',
            pagination: {
                total: 5,
                page: '1',
                limit: '10',
                totalPage: 1
            },
            data: [
                {
                    id: 1,
                    name: 'IT',
                    status: 'active'
                }
            ]
        },
        examples: [
            {
                title: 'List Departments',
                description: 'Retrieve a paginated list of departments.',
                url: '/api/departments?page=1&limit=10',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Departments retrieved successfully',
                    pagination: { total: 5, page: '1', limit: '10', totalPage: 1 },
                    data: [{ id: 1, name: 'IT', status: 'active' }]
                }
            }
        ]
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [validate(createDepartment)],
        handler: handlerWithFields((req, res) => departmentController.createDepartment(req, res), createDepartment),
        description: 'Create a new department',
        database: {
            tables: ['departments'],
            mainTable: 'departments',
            requiredFields: ['name'],
            optionalFields: ['description', 'head_id', 'status'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            name: 'Human Resources',
            description: 'Manages HR operations and staff'
        },
        sampleResponse: {
            status: true,
            message: 'Department created successfully',
            data: {
                id: 1,
                name: 'Human Resources'
            }
        },
        examples: [
            {
                title: 'Create Department',
                description: 'Add a new department to the organization.',
                url: '/api/departments',
                method: 'POST',
                request: {
                    name: 'Human Resources',
                    description: 'Manages HR operations and staff',
                    head_id: 2,
                    status: 'active'
                },
                response: {
                    status: true,
                    message: 'Department created successfully',
                    data: { id: 2, name: 'Human Resources' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => departmentController.getDepartmentById(req, res),
        description: 'Get department details',
        database: {
            tables: ['departments', 'staffs'],
            mainTable: 'departments',
            fields: {
                departments: ['id', 'name', 'description', 'head_id', 'status', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name']
            },
            relationships: ['departments.head_id -> staffs.id (FK)']
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                name: 'IT',
                head: {
                    first_name: 'John',
                    last_name: 'Doe'
                }
            }
        },
        examples: [
            {
                title: 'Get Department',
                description: 'Retrieve detailed information about a specific department.',
                url: '/api/departments/1',
                method: 'GET',
                response: {
                    status: true,
                    data: { id: 1, name: 'IT', head: { first_name: 'John', last_name: 'Doe' } }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updateDepartment)],
        handler: handlerWithFields((req, res) => departmentController.updateDepartment(req, res), updateDepartment),
        description: 'Update department',
        database: {
            tables: ['departments'],
            mainTable: 'departments',
            updatableFields: ['name', 'description', 'head_id', 'status'],
            readOnlyFields: ['id', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            name: 'Information Technology',
            description: 'IT Department'
        },
        sampleResponse: {
            status: true,
            message: 'Department updated successfully'
        },
        examples: [
            {
                title: 'Update Department',
                description: 'Update the details of an existing department.',
                url: '/api/departments/1',
                method: 'PUT',
                request: {
                    name: 'Information Technology',
                    description: 'IT Department',
                    status: 'active'
                },
                response: {
                    status: true,
                    message: 'Department updated successfully'
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => departmentController.deleteDepartment(req, res),
        description: 'Delete department',
        database: {
            tables: ['departments', 'staffs'],
            mainTable: 'departments',
            sideEffects: ['Check for associated staffs before deletion']
        },
        sampleResponse: {
            status: true,
            message: 'Department deleted successfully'
        },
        examples: [
            {
                title: 'Delete Department',
                description: 'Remove a department from the organization.',
                url: '/api/departments/2',
                method: 'DELETE',
                response: {
                    status: true,
                    message: 'Department deleted successfully'
                }
            }
        ]
    }
];

// Register routes
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
