const express = require('express');
const router = express.Router();
const payrollController = require('./payroll.controller');
const { verifyToken } = require('../../core/middleware/auth');
const validate = require('../../core/middleware/validate');
const { generateRun } = require('./payroll.validation');
const { handlerWithFields } = require('../../core/utils/zodTypeView');

// Module name for routes-tree grouping
router.moduleName = 'Payroll';

router.use(verifyToken);

router.routesMeta = [
    {
        path: '/generate',
        method: 'POST',
        middlewares: [validate(generateRun)],
        handler: handlerWithFields((req, res) => payrollController.generateRun(req, res), generateRun),
        description: 'Generate a new payroll run for a specific month',
        database: {
            tables: ['payroll_runs', 'payroll_items', 'users'],
            mainTable: 'payroll_runs',
            requiredFields: ['month'],
            autoGeneratedFields: ['id', 'status', 'total_gross', 'total_net', 'created_at']
        },
        sampleRequest: {
            month: '2025-01'
        },
        sampleResponse: {
            success: true,
            message: 'Payroll run generated successfully',
            data: {
                id: 1,
                month: '2025-01',
                total_gross: 50000.00,
                total_net: 50000.00,
                status: 'pending',
                items: [
                    {
                        staff_id: 1,
                        basic_salary: 50000.00,
                        net_pay: 50000.00
                    }
                ]
            }
        },
        examples: [
            {
                title: 'Generate Run',
                description: 'Generate payroll for Jan 2025',
                url: '/api/payroll/generate',
                method: 'POST',
                request: { month: '2025-01' },
                response: { status: true, data: { id: 1, month: '2025-01' } }
            }
        ]
    },
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => payrollController.getRuns(req, res),
        description: 'Get all payroll runs',
        database: {
            tables: ['payroll_runs'],
            mainTable: 'payroll_runs',
            fields: {
                payroll_runs: ['id', 'month', 'total_gross', 'total_net', 'status', 'payment_date', 'created_at']
            }
        },
        queryParams: {
            page: 'Page number',
            limit: 'Items per page',
            status: 'Filter by status (pending, approved, paid)',
            month: 'Filter by month'
        },
        sampleResponse: {
            success: true,
            message: 'Payroll runs retrieved successfully',
            data: [
                {
                    id: 1,
                    month: '2025-01',
                    status: 'pending'
                }
            ]
        }
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => payrollController.getRunById(req, res),
        description: 'Get payroll run details with items',
        database: {
            tables: ['payroll_runs', 'payroll_items'],
            mainTable: 'payroll_runs',
            relationships: ['payroll_runs.hasMany(payroll_items)']
        },
        sampleResponse: {
            success: true,
            data: {
                id: 1,
                month: '2025-01',
                items: []
            }
        }
    },
    {
        path: '/:id/approve',
        method: 'PATCH',
        middlewares: [],
        handler: (req, res) => payrollController.approveRun(req, res),
        description: 'Approve a payroll run',
        database: {
            tables: ['payroll_runs'],
            mainTable: 'payroll_runs',
            updatableFields: ['status']
        }
    },
    {
        path: '/:id/pay',
        method: 'PATCH',
        middlewares: [],
        handler: (req, res) => payrollController.payRun(req, res),
        description: 'Mark payroll run as paid and create expense',
        database: {
            tables: ['payroll_runs', 'expenses'],
            mainTable: 'payroll_runs',
            sideEffects: ['Creates an Expense record for total net salary']
        }
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => payrollController.deleteRun(req, res),
        description: 'Delete a payroll run (if not paid)',
        database: {
            tables: ['payroll_runs', 'payroll_items'],
            sideEffects: ['Deletes associated payroll items']
        }
    },
    {
        path: '/structure/:staffId',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => payrollController.getStructure(req, res),
        description: 'Get payroll structure for a staff',
        database: { tables: ['payroll_structures'] },
        sampleResponse: {
            status: true,
            message: 'Payroll structure retrieved',
            data: {
                staff_id: 101,
                basic_salary: 5000.00,
                allowances: [{ title: 'Rent', amount: 1000, type: 'fixed' }],
                deductions: [{ title: 'Tax', amount: 200, type: 'fixed' }],
                bank_details: { bank_name: 'Chase', account_number: '123' },
                net_salary: 5800.00
            }
        },
        examples: [
            {
                title: 'Get Structure',
                description: 'Get salary configuration for staff 101',
                url: '/api/payroll/structure/101',
                method: 'GET',
                response: {
                    status: true,
                    data: { staff_id: 101, net_salary: 5800.00 }
                }
            }
        ]
    },
    {
        path: '/structure/:staffId',
        method: 'POST',
        middlewares: [],
        handler: (req, res) => payrollController.saveStructure(req, res),
        description: 'Save/Update payroll structure for a staff',
        database: {
            tables: ['payroll_structures'],
            requiredFields: ['basic_salary']
        },
        sampleRequest: {
            basic_salary: 5000.00,
            allowances: [{ title: 'Rent', amount: 1000, type: 'fixed' }],
            deductions: [{ title: 'Tax', amount: 200, type: 'fixed' }],
            bank_details: { bank_name: 'Chase', account_number: '123456789' }
        },
        sampleResponse: {
            status: true,
            message: 'Payroll structure saved',
            data: {
                id: 5,
                staff_id: 101,
                basic_salary: 5000.00,
                updated_at: '2026-01-15T12:00:00Z'
            }
        },
        examples: [
            {
                title: 'Update Structure',
                description: 'Update salary details for staff 101',
                url: '/api/payroll/structure/101',
                method: 'POST',
                request: {
                    basic_salary: 6000.00,
                    allowances: []
                },
                response: {
                    status: true,
                    message: 'Payroll structure saved',
                    data: { staff_id: 101, basic_salary: 6000.00 }
                }
            }
        ]
    }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
