const express = require('express');
const router = express.Router();
const payrollController = require('./payroll.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createPayroll, updatePayroll } = require('./payroll.validation');

// Module name for routes-tree grouping
router.moduleName = 'Payroll';

router.use(verifyToken);
router.use(moduleCheck('payroll')); // Ensure 'payroll' module is enabled in settings if applicable

// Define routes metadata
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => payrollController.getPayrolls(req, res),
        description: 'List all payroll records',
        database: {
            tables: ['payroll', 'staffs'],
            mainTable: 'payroll',
            fields: {
                payroll: ['id', 'staff_id', 'month', 'year', 'basic_salary', 'allowances', 'deductions', 'net_salary', 'status', 'payment_date', 'payment_method', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name', 'salary']
            },
            relationships: ['payroll.staff_id -> staffs.id (FK)']
        },
        queryParams: {
            staff_id: 'Filter by staff ID',
            month: 'Filter by month',
            year: 'Filter by year',
            status: 'Filter by status',
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Payroll records retrieved successfully',
            pagination: {
                total: 50,
                page: '1',
                limit: '10',
                totalPage: 5
            },
            data: [
                {
                    id: 1,
                    staff_id: 5,
                    month: 'December',
                    year: 2025,
                    basic_salary: '5000.00',
                    net_salary: '5500.00',
                    status: 'pending',
                    staff: {
                        first_name: 'John',
                        last_name: 'Doe'
                    }
                }
            ]
        }
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [validate(createPayroll)],
        handler: handlerWithFields((req, res) => payrollController.createPayroll(req, res), createPayroll),
        description: 'Create a new payroll record',
        database: {
            tables: ['payroll'],
            mainTable: 'payroll',
            requiredFields: ['staff_id', 'month', 'year', 'basic_salary'],
            optionalFields: ['allowances', 'deductions', 'status', 'payment_date', 'payment_method'],
            autoGeneratedFields: ['id', 'net_salary', 'created_at', 'updated_at'],
            sideEffects: ['Calculates net_salary from basic_salary + allowances - deductions']
        },
        sampleRequest: {
            staff_id: 5,
            month: 'December',
            year: 2025,
            basic_salary: 5000.00,
            allowances: {
                transport: 200,
                housing: 500
            },
            deductions: {
                tax: 100,
                epf: 100
            },
            status: 'pending'
        },
        sampleResponse: {
            status: true,
            message: 'Payroll record created successfully',
            data: {
                id: 1,
                net_salary: 5500.00
            }
        }
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => payrollController.getPayrollById(req, res),
        description: 'Get payroll details',
        database: {
            tables: ['payroll', 'staffs'],
            mainTable: 'payroll',
            fields: {
                payroll: ['id', 'staff_id', 'month', 'year', 'basic_salary', 'allowances', 'deductions', 'net_salary', 'status', 'payment_date', 'payment_method', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name', 'salary']
            },
            relationships: ['payroll.staff_id -> staffs.id (FK)']
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                allowances: {},
                deductions: {}
            }
        }
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updatePayroll)],
        handler: handlerWithFields((req, res) => payrollController.updatePayroll(req, res), updatePayroll),
        description: 'Update payroll record',
        database: {
            tables: ['payroll'],
            mainTable: 'payroll',
            updatableFields: ['basic_salary', 'allowances', 'deductions', 'status', 'payment_date', 'payment_method'],
            readOnlyFields: ['id', 'staff_id', 'month', 'year', 'created_at'],
            autoUpdatedFields: ['net_salary', 'updated_at'],
            sideEffects: ['Recalculates net_salary if basic_salary, allowances, or deductions change']
        },
        sampleRequest: {
            status: 'paid',
            payment_date: '2025-12-31',
            payment_method: 'bank_transfer'
        },
        sampleResponse: {
            status: true,
            message: 'Payroll record updated successfully'
        }
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => payrollController.deletePayroll(req, res),
        description: 'Delete payroll record',
        database: {
            tables: ['payroll'],
            mainTable: 'payroll'
        },
        sampleResponse: {
            status: true,
            message: 'Payroll record deleted successfully'
        }
    }
];

// Register routes
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
