const express = require('express');
const router = express.Router();
const accountingController = require('./accounting.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createIncome, createExpense, createPayroll } = require('./accounting.validation');

// Module name for routes-tree grouping
router.moduleName = 'Accounting';

router.use(verifyToken);
router.use(moduleCheck('accounting'));

// Define routes metadata
router.routesMeta = [
    // --- Overview ---
    {
        path: '/overview',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => accountingController.getOverview(req, res),
        description: 'Get financial overview',
        database: {
            tables: ['incomes', 'expenses', 'payroll'],
            mainTable: 'incomes',
            fields: {
                incomes: ['amount', 'income_date'],
                expenses: ['amount', 'expense_date'],
                payroll: ['net_salary', 'payment_date']
            },
            sideEffects: ['Aggregates data from multiple tables to calculate totals']
        },
        queryParams: {
            start_date: 'Filter by start date (YYYY-MM-DD)',
            end_date: 'Filter by end date (YYYY-MM-DD)'
        },
        sampleResponse: {
            status: true,
            data: {
                total_income: 50000.00,
                total_expense: 20000.00,
                total_payroll: 15000.00,
                net_profit: 15000.00
            }
        }
    },

    // --- Incomes ---
    {
        path: '/incomes',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => accountingController.getIncomes(req, res),
        description: 'List all income records',
        database: {
            tables: ['incomes'],
            mainTable: 'incomes',
            fields: {
                incomes: ['id', 'title', 'amount', 'income_date', 'category', 'description', 'created_at', 'updated_at']
            }
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Income records retrieved successfully',
            pagination: {
                total: 50,
                page: '1',
                limit: '10',
                totalPage: 5
            },
            data: [
                {
                    id: 1,
                    title: 'Service Revenue',
                    amount: 1000.00,
                    income_date: '2025-01-15'
                }
            ]
        }
    },
    {
        path: '/incomes',
        method: 'POST',
        middlewares: [validate(createIncome)],
        handler: handlerWithFields((req, res) => accountingController.createIncome(req, res), createIncome),
        description: 'Add a new income record',
        database: {
            tables: ['incomes'],
            mainTable: 'incomes',
            requiredFields: ['title', 'amount', 'income_date'],
            optionalFields: ['category', 'description'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            title: 'Consulting Fee',
            amount: 500.00,
            income_date: '2025-01-20',
            category: 'Services'
        },
        sampleResponse: {
            status: true,
            message: 'Income record created successfully'
        }
    },

    // --- Expenses ---
    {
        path: '/expenses',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => accountingController.getExpenses(req, res),
        description: 'List all expense records',
        database: {
            tables: ['expenses'],
            mainTable: 'expenses',
            fields: {
                expenses: ['id', 'title', 'amount', 'expense_date', 'category', 'description', 'created_at', 'updated_at']
            }
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Expense records retrieved successfully',
            pagination: {
                total: 50,
                page: '1',
                limit: '10',
                totalPage: 5
            },
            data: [
                {
                    id: 1,
                    title: 'Office Rent',
                    amount: 2000.00,
                    expense_date: '2025-01-01'
                }
            ]
        }
    },
    {
        path: '/expenses',
        method: 'POST',
        middlewares: [validate(createExpense)],
        handler: handlerWithFields((req, res) => accountingController.createExpense(req, res), createExpense),
        description: 'Add a new expense record',
        database: {
            tables: ['expenses'],
            mainTable: 'expenses',
            requiredFields: ['title', 'amount', 'expense_date'],
            optionalFields: ['category', 'description'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            title: 'Internet Bill',
            amount: 100.00,
            expense_date: '2025-01-05',
            category: 'Utilities'
        },
        sampleResponse: {
            status: true,
            message: 'Expense record created successfully'
        }
    },

    // --- Payroll ---
    {
        path: '/payroll',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => accountingController.getPayrolls(req, res),
        description: 'List all payroll records',
        database: {
            tables: ['payroll', 'staffs'],
            mainTable: 'payroll',
            fields: {
                payroll: ['id', 'staff_id', 'salary_month', 'basic_salary', 'deductions', 'net_salary', 'status', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name']
            },
            relationships: ['payroll.staff_id -> staffs.id (FK)']
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Payroll records retrieved successfully',
            pagination: {
                total: 50,
                page: '1',
                limit: '10',
                totalPage: 5
            },
            data: [
                {
                    id: 1,
                    staff_id: 1,
                    salary_month: '2025-01',
                    net_salary: 4500.00,
                    status: 'paid'
                }
            ]
        }
    },
    {
        path: '/payroll',
        method: 'POST',
        middlewares: [validate(createPayroll)],
        handler: handlerWithFields((req, res) => accountingController.createPayroll(req, res), createPayroll),
        description: 'Add a new payroll record',
        database: {
            tables: ['payroll'],
            mainTable: 'payroll',
            requiredFields: ['staff_id', 'salary_month', 'basic_salary'],
            optionalFields: ['deductions', 'status'],
            autoGeneratedFields: ['id', 'net_salary', 'created_at', 'updated_at'],
            sideEffects: ['Calculates net_salary from basic_salary - deductions']
        },
        sampleRequest: {
            staff_id: 1,
            salary_month: '2025-01',
            basic_salary: 5000.00,
            deductions: 500.00,
            status: 'processed'
        },
        sampleResponse: {
            status: true,
            message: 'Payroll record created successfully'
        }
    }
];

// Register routes
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
