const express = require('express');
const router = express.Router();
const controller = require('./user.controller');
const validate = require('../../core/middleware/validate');
const { verifyToken } = require('../../core/middleware/auth');
const { createSchema, updateSchema } = require('./user.validation');
const { handlerWithFields } = require('../../core/utils/zodTypeView');

router.moduleName = 'Users';

// Define routes metadata with comprehensive documentation
router.routesMeta = [
  {
    path: '/add',
    method: 'POST',
    middlewares: [verifyToken, validate(createSchema)],
    handler: handlerWithFields(controller.create, createSchema),
    description: 'Create a new user account',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      requiredFields: ['name', 'email', 'password', 'role_id'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at'],
      relationships: ['users.role_id -> roles.id (FK)']
    },
    sampleRequest: {
      name: 'John Doe',
      email: 'john.doe@example.com',
      password: 'SecurePassword123!',
      role_id: 2
    },
    sampleResponse: {
      status: true,
      message: 'created',
      data: {
        id: 15,
        name: 'John Doe',
        email: 'john.doe@example.com',
        role_id: 2,
        created_at: '2025-12-02T10:00:00.000Z'
      },
      code: 201
    }
  },
  {
    path: '/update/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateSchema)],
    handler: handlerWithFields(controller.update, updateSchema),
    description: 'Update an existing user by ID',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      updatableFields: ['name', 'email', 'role_id'],
      readOnlyFields: ['id', 'created_at'],
      autoUpdatedFields: ['updated_at'],
      relationships: ['users.role_id -> roles.id (FK)']
    },
    sampleRequest: {
      name: 'John Smith',
      email: 'john.smith@example.com',
      role_id: 3
    },
    sampleResponse: {
      status: true,
      message: 'updated',
      data: {
        id: 15,
        name: 'John Smith',
        email: 'john.smith@example.com',
        role_id: 3,
        updated_at: '2025-12-02T10:05:00.000Z'
      }
    }
  },
  {
    path: '/',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.getAllUsers,
    description: 'Get all users with pagination',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      fields: {
        users: ['id', 'name', 'email', 'role_id', 'created_at', 'updated_at'],
        roles: ['id', 'name', 'description']
      },
      relationships: ['users.role_id -> roles.id (FK)']
    },
    queryParams: {
      page: 'Page number (default: 1)',
      limit: 'Items per page (default: 10)',
      role_id: 'Filter by role ID',
      search: 'Search by name or email'
    },
    sampleResponse: {
      success: true,
      message: 'Users retrieved successfully',
      pagination: {
        total: 3,
        page: '1',
        limit: '10',
        totalPage: 1
      },
      data: [
        {
          id: 1,
          name: 'Admin User',
          email: 'admin@erp.com',
          role_id: 1,
          role: {
            id: 1,
            name: 'Admin'
          },
          created_at: '2025-12-03T05:00:00.000Z'
        }
      ]
    }
  },
  {
    path: '/get/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.get,
    description: 'Get a specific user by ID with role information',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      fields: {
        users: ['id', 'name', 'email', 'role_id', 'created_at', 'updated_at'],
        roles: ['id', 'name', 'description']
      },
      relationships: ['users.role_id -> roles.id (FK)']
    },
    sampleResponse: {
      status: true,
      message: 'user',
      data: {
        id: 1,
        name: 'Admin User',
        email: 'admin@example.com',
        role_id: 1,
        role: {
          id: 1,
          name: 'Admin',
          description: 'Full system access'
        },
        created_at: '2025-12-01T00:00:00.000Z'
      }
    }
  },
  {
    path: '/delete/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: controller.remove,
    description: 'Delete a user by ID (soft delete)',
    database: {
      tables: ['users'],
      mainTable: 'users',
      sideEffects: ['Soft delete - sets deleted_at timestamp or is_active flag']
    },
    sampleResponse: {
      status: true,
      message: 'deleted',
      data: null
    }
  },
];

// Apply routes
router.post('/add', verifyToken, validate(createSchema), handlerWithFields(controller.createUser, createSchema));
router.put('/update/:id', verifyToken, validate(updateSchema), handlerWithFields(controller.updateUser, updateSchema));
router.delete('/delete/:id', verifyToken, controller.deleteUser);
router.get('/get/:id', verifyToken, controller.getUserById);
router.get('/', verifyToken, controller.getAllUsers);

module.exports = router;
