const express = require('express');
const router = express.Router();
const controller = require('./user.controller');
const validate = require('../../core/middleware/validate');
const { verifyToken } = require('../../core/middleware/auth');
const { createSchema, updateSchema } = require('./user.validation');
const { handlerWithFields } = require('../../core/utils/zodTypeView');

router.moduleName = 'Users';

// Define routes metadata with comprehensive documentation
router.routesMeta = [
  {
    path: '/add',
    method: 'POST',
    middlewares: [verifyToken, validate(createSchema)],
    handler: handlerWithFields((req, res) => controller.createUser(req, res), createSchema),
    description: 'Create a new user account',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      requiredFields: ['name', 'email', 'password', 'role_id'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at'],
      relationships: ['users.role_id -> roles.id (FK)']
    },
    sampleRequest: {
      name: 'John Doe',
      email: 'john.doe@example.com',
      password: 'SecurePassword123!',
      role_id: 2
    },
    sampleResponse: {
      status: true,
      message: 'created',
      data: {
        id: 15,
        name: 'John Doe',
        email: 'john.doe@example.com',
        role_id: 2,
        created_at: '2025-12-02T10:00:00.000Z'
      },
      code: 201
    },
    examples: [
      {
        title: 'Create User',
        description: 'Register a new user',
        url: '/api/users/add',
        method: 'POST',
        request: {
          name: 'Alice Wonder',
          email: 'alice@example.com',
          password: 'password123',
          role_id: 2
        },
        response: {
          status: true,
          message: 'created',
          data: { id: 16, name: 'Alice Wonder', email: 'alice@example.com' }
        }
      }
    ]
  },
  {
    path: '/update/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateSchema)],
    handler: handlerWithFields((req, res) => controller.updateUser(req, res), updateSchema),
    description: 'Update an existing user by ID',
    database: {
      tables: ['users', 'roles', 'departments'],
      mainTable: 'users',
      updatableFields: [
        'name', 'first_name', 'last_name', 'email', 'password', 'role_id',
        'phone', 'position', 'department_id', 'hire_date', 'salary',
        'address', 'city', 'state', 'country', 'postal_code',
        'status', 'notes', 'thumb_url', 'gallery_items'
      ],
      readOnlyFields: ['id', 'created_at'],
      autoUpdatedFields: ['updated_at'],
      relationships: [
        'users.role_id -> roles.id (FK)',
        'users.department_id -> departments.id (FK)'
      ]
    },
    sampleRequest: {
      name: 'John Smith',
      email: 'john.smith@example.com',
      password: 'newSecurePassword123',
      status: 'active',
      role_id: 3,
      position: 'Senior Manager',
      salary: 85000
    },
    sampleResponse: {
      status: true,
      message: 'updated',
      data: {
        id: 15,
        name: 'John Smith',
        email: 'john.smith@example.com',
        role_id: 3,
        status: 'active',
        position: 'Senior Manager',
        updated_at: '2025-12-02T10:05:00.000Z'
      }
    },
    examples: [
      {
        title: 'Update User Basic Info',
        description: 'Update user name and role',
        url: '/api/users/update/16',
        method: 'PUT',
        request: { name: 'Alice W.', role_id: 3 },
        response: {
          status: true,
          message: 'updated',
          data: { id: 16, name: 'Alice W.', role_id: 3 }
        }
      },
      {
        title: 'Update User Password and Status',
        description: 'Update user password and change status',
        url: '/api/users/update/16',
        method: 'PUT',
        request: {
          password: 'newPassword456',
          status: 'inactive'
        },
        response: {
          status: true,
          message: 'updated',
          data: {
            id: 16,
            name: 'Alice W.',
            status: 'inactive',
            updated_at: '2025-12-02T10:10:00.000Z'
          }
        }
      }
    ]
  },
  {
    path: '/',
    method: 'GET',
    middlewares: [verifyToken],
    handler: (req, res) => controller.getAllUsers(req, res),
    description: 'Get all users with pagination',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      fields: {
        users: ['id', 'name', 'first_name', 'last_name', 'email', 'role_id', 'department_id', 'status', 'created_at', 'updated_at'],
        roles: ['id', 'name', 'description']
      },
      relationships: ['users.role_id -> roles.id (FK)']
    },
    queryParams: {
      page: 'Page number (default: 1)',
      limit: 'Items per page (default: 10)',
      role_id: 'Filter by role ID',
      department_id: 'Filter by department ID',
      status: 'Filter by status (active/inactive)',
      search: 'Search by name, first_name, last_name, or email'
    },
    sampleResponse: {
      success: true,
      message: 'Users retrieved successfully',
      pagination: {
        total: 3,
        page: '1',
        limit: '10',
        totalPage: 1
      },
      data: [
        {
          id: 1,
          name: 'Admin User',
          email: 'admin@erp.com',
          role_id: 1,
          role: {
            id: 1,
            name: 'Admin'
          },
          created_at: '2025-12-03T05:00:00.000Z'
        }
      ]
    },
    examples: [
      {
        title: 'List Users',
        description: 'Get all users',
        url: '/api/users?page=1&limit=10',
        method: 'GET',
        response: {
          success: true,
          message: 'Users retrieved successfully',
          data: [{ id: 1, name: 'Admin User' }]
        }
      }
    ]
  },
  {
    path: '/get/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: (req, res) => controller.getUserById(req, res),
    description: 'Get a specific user by ID with role information',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      fields: {
        users: ['id', 'name', 'email', 'role_id', 'created_at', 'updated_at'],
        roles: ['id', 'name', 'description']
      },
      relationships: ['users.role_id -> roles.id (FK)']
    },
    sampleResponse: {
      status: true,
      message: 'user',
      data: {
        id: 1,
        name: 'Admin User',
        email: 'admin@example.com',
        role_id: 1,
        role: {
          id: 1,
          name: 'Admin',
          description: 'Full system access'
        },
        created_at: '2025-12-01T00:00:00.000Z'
      }
    },
    examples: [
      {
        title: 'Get User',
        description: 'Get user by ID',
        url: '/api/users/get/1',
        method: 'GET',
        response: {
          status: true,
          message: 'user',
          data: { id: 1, name: 'Admin User' }
        }
      }
    ]
  },
  {
    path: '/delete/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: (req, res) => controller.deleteUser(req, res),
    description: 'Delete a user by ID (soft delete)',
    database: {
      tables: ['users'],
      mainTable: 'users',
      sideEffects: ['Soft delete - sets deleted_at timestamp or is_active flag']
    },
    sampleResponse: {
      status: true,
      message: 'deleted',
      data: null
    },
    examples: [
      {
        title: 'Delete User',
        description: 'Remove a user',
        url: '/api/users/delete/16',
        method: 'DELETE',
        response: {
          status: true,
          message: 'deleted',
          data: null
        }
      }
    ]
  },
];

// Register routes from metadata
router.routesMeta.forEach(r => {
  router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
