const express = require('express');
const router = express.Router();
const attendanceController = require('./attendance.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { checkIn, checkOut, updateAttendance } = require('./attendance.validation');

// Module name for routes-tree grouping
router.moduleName = 'Attendance';

router.use(verifyToken);
router.use(moduleCheck('attendance'));

// Define routes metadata
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => attendanceController.getAttendances(req, res),
        description: 'List attendance records',
        database: {
            tables: ['attendance', 'staffs'],
            mainTable: 'attendance',
            fields: {
                attendance: ['id', 'staff_id', 'date', 'check_in', 'check_out', 'status', 'notes', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name']
            },
            relationships: ['attendance.staff_id -> staffs.id (FK)']
        },
        queryParams: {
            staff_id: 'Filter by staff ID',
            date: 'Filter by date',
            status: 'Filter by status',
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Attendance records retrieved successfully',
            pagination: {
                total: 50,
                page: '1',
                limit: '10',
                totalPage: 5
            },
            data: [
                {
                    id: 1,
                    staff_id: 5,
                    date: '2025-12-02',
                    check_in: '09:00:00',
                    check_out: '18:00:00',
                    status: 'present'
                }
            ]
        }
    },
    {
        path: '/check-in',
        method: 'POST',
        middlewares: [validate(checkIn)],
        handler: handlerWithFields((req, res) => attendanceController.checkIn(req, res), checkIn),
        description: 'Staff Check-in',
        database: {
            tables: ['attendance'],
            mainTable: 'attendance',
            requiredFields: ['staff_id', 'date', 'check_in'],
            optionalFields: ['status', 'notes'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            staff_id: 5,
            date: '2025-12-02',
            check_in: '09:00:00',
            status: 'present'
        },
        sampleResponse: {
            status: true,
            message: 'Checked in successfully'
        }
    },
    {
        path: '/check-out',
        method: 'POST',
        middlewares: [validate(checkOut)],
        handler: handlerWithFields((req, res) => attendanceController.checkOut(req, res), checkOut),
        description: 'Staff Check-out',
        database: {
            tables: ['attendance'],
            mainTable: 'attendance',
            requiredFields: ['staff_id', 'date', 'check_out'],
            sideEffects: ['Updates existing attendance record with check_out time']
        },
        sampleRequest: {
            staff_id: 5,
            date: '2025-12-02',
            check_out: '18:00:00'
        },
        sampleResponse: {
            status: true,
            message: 'Checked out successfully'
        }
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => attendanceController.getAttendanceById(req, res),
        description: 'Get attendance details',
        database: {
            tables: ['attendance', 'staffs'],
            mainTable: 'attendance',
            fields: {
                attendance: ['id', 'staff_id', 'date', 'check_in', 'check_out', 'status', 'notes', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name']
            },
            relationships: ['attendance.staff_id -> staffs.id (FK)']
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                staff_id: 5,
                date: '2025-12-02'
            }
        }
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updateAttendance)],
        handler: handlerWithFields((req, res) => attendanceController.updateAttendance(req, res), updateAttendance),
        description: 'Update attendance record',
        database: {
            tables: ['attendance'],
            mainTable: 'attendance',
            updatableFields: ['check_in', 'check_out', 'status', 'notes'],
            readOnlyFields: ['id', 'staff_id', 'date', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            status: 'late',
            notes: 'Traffic delay'
        },
        sampleResponse: {
            status: true,
            message: 'Attendance updated successfully'
        }
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => attendanceController.deleteAttendance(req, res),
        description: 'Delete attendance record',
        database: {
            tables: ['attendance'],
            mainTable: 'attendance'
        },
        sampleResponse: {
            status: true,
            message: 'Attendance deleted successfully'
        }
    }
];

// Register routes
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
