const express = require('express');
const router = express.Router();
const controller = require('./role.controller');
const validate = require('../../core/middleware/validate');
const { verifyToken } = require('../../core/middleware/auth');
const { createSchema, updateSchema } = require('./role.validation');
const { createMenuSchema, updateMenuSchema } = require('./role_menu.validation');
const { createDashboardSchema, updateDashboardSchema } = require('./role_dashboard.validation');
const menuController = require('./role_menu.controller');
const dashboardController = require('./role_dashboard.controller');
const { handlerWithFields } = require('../../core/utils/zodTypeView');

// Module name for routes-tree grouping
router.moduleName = 'Roles';

// Define routes metadata with comprehensive documentation
router.routesMeta = [
  {
    path: '/add',
    method: 'POST',
    middlewares: [verifyToken, validate(createSchema)],
    handler: handlerWithFields(controller.create, createSchema),
    description: 'Create a new role with settings',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      requiredFields: ['name'],
      optionalFields: ['menu', 'dashboard', 'custom'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at'],
      relationships: [
        'role_settings.role_id -> roles.id (FK)'
      ],
      sideEffects: ['Creates role_settings entry']
    },
    sampleRequest: {
      role: 'Regional Sales Manager',
      display_name: 'Regional Sales Department Manager',
      description: 'Manages regional sales team and operations',
      status: 'active',
      permissions: ['sales.view', 'sales.create'],
      menu: ['sales', 'dashboard'],
      dashboard: ['overview', 'revenue'],
      custom: { theme: 'dark' }
    },
    sampleResponse: {
      status: true,
      message: 'created',
      data: {
        id: 5,
        role: 'Sales Manager',
        display_name: 'Sales Department Manager',
        description: 'Manages sales team and operations',
        status: 'active',
        permissions: ['sales.view', 'sales.create'],
        settings: {
          menu: ['sales', 'dashboard'],
          dashboard: ['overview', 'revenue'],
          custom: { theme: 'dark' }
        }
      }
    },
    examples: [
      {
        title: 'Create new role',
        description: 'Create a new role with specific permissions and menu settings',
        url: '/api/roles/add',
        method: 'POST',
        request: {
          name: 'Regional Manager',
          display_name: 'Regional Sales Manager',
          description: 'Oversees regional sales operations',
          status: 'active',
          permissions: ['sales.view', 'sales.create', 'reports.view'],
          menu: ['sales', 'dashboard', 'reports'],
          dashboard: ['overview', 'regional_stats'],
          custom: { region: 'North' }
        },
        response: {
          status: true,
          message: 'created',
          data: {
            id: 10,
            role: 'Regional Manager',
            display_name: 'Regional Sales Manager',
            status: 'active',
            settings: {
              menu: ['sales', 'dashboard', 'reports'],
              dashboard: ['overview', 'regional_stats'],
              custom: { region: 'North' }
            }
          }
        }
      }
    ]
  },
  {
    path: '/update/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateSchema)],
    handler: handlerWithFields(controller.update, updateSchema),
    description: 'Update an existing role by ID',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      updatableFields: ['name', 'menu', 'dashboard', 'custom'],
      readOnlyFields: ['id', 'created_at'],
      autoUpdatedFields: ['updated_at'],
      relationships: [
        'role_settings.role_id -> roles.id (FK)'
      ],
      sideEffects: ['Updates role_settings entry']
    },
    sampleRequest: {
      name: 'Senior Sales Manager',
      menu: ['sales', 'dashboard', 'reports'],
      dashboard: ['overview', 'revenue', 'analytics'],
      custom: { theme: 'light' }
    },
    sampleResponse: {
      status: true,
      message: 'updated',
      data: {
        id: 5,
        name: 'Senior Sales Manager',
        settings: {
          menu: ['sales', 'dashboard', 'reports'],
          dashboard: ['overview', 'revenue', 'analytics'],
          custom: { theme: 'light' }
        }
      }
    },
    examples: [
      {
        title: 'Update role settings',
        description: 'Update permissions and dashboard settings for a role',
        url: '/api/roles/update/10',
        method: 'PUT',
        request: {
          display_name: 'Senior Regional Manager',
          permissions: ['sales.view', 'sales.create', 'reports.view', 'reports.export'],
          dashboard: ['overview', 'regional_stats', 'performance']
        },
        response: {
          status: true,
          message: 'updated',
          data: {
            id: 10,
            name: 'Regional Manager',
            display_name: 'Senior Regional Manager',
            settings: {
              dashboard: ['overview', 'regional_stats', 'performance']
            }
          }
        }
      }
    ]
  },
  {
    path: '/list',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.list,
    description: 'Get paginated list of all roles',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      fields: {
        roles: ['id', 'name', 'created_at'],
        role_settings: ['menu', 'dashboard', 'custom']
      }
    },
    queryParams: {
      page: '1 (default)',
      limit: '10 (default)'
    },
    sampleResponse: {
      success: true,
      message: 'Roles retrieved successfully',
      pagination: {
        total: 5,
        page: '1',
        limit: '10',
        totalPage: 1
      },
      data: [
        {
          id: 1,
          role: 'Admin',
          display_name: 'System Administrator',
          description: 'Full system access',
          status: 'active',
          permissions: ['*'],
          settings: {
            menu: ['all'],
            dashboard: ['main'],
            custom: {}
          }
        }
      ]
    },
    examples: [
      {
        title: 'List all roles',
        description: 'Retrieve a paginated list of all system roles',
        url: '/api/roles/list?page=1&limit=10',
        method: 'GET',
        response: {
          success: true,
          message: 'Roles retrieved successfully',
          pagination: { total: 5, page: '1', limit: '10', totalPage: 1 },
          data: [
            {
              id: 1,
              role: 'Admin',
              display_name: 'Administrator',
              status: 'active'
            },
            {
              id: 2,
              role: 'User',
              display_name: 'Standard User',
              status: 'active'
            }
          ]
        }
      }
    ]
  },
  {
    path: '/get/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.get,
    description: 'Get a specific role by ID with settings',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      fields: {
        roles: ['id', 'name', 'created_at'],
        role_settings: ['menu', 'dashboard', 'custom']
      },
      relationships: [
        'role_settings.role_id -> roles.id (FK)'
      ]
    },
    sampleResponse: {
      status: true,
      message: 'Role retrieved successfully',
      data: {
        id: 1,
        name: 'Admin',
        settings: {
          menu: ['all'],
          dashboard: ['main'],
          custom: {}
        }
      }
    },
    examples: [
      {
        title: 'Get role details',
        description: 'Retrieve detailed information for a specific role',
        url: '/api/roles/get/1',
        method: 'GET',
        response: {
          status: true,
          message: 'Role retrieved successfully',
          data: {
            id: 1,
            name: 'Admin',
            display_name: 'Administrator',
            permissions: ['*'],
            settings: {
              menu: ['all'],
              dashboard: ['main'],
              custom: {}
            }
          }
        }
      }
    ]
  },
  {
    path: '/delete/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: controller.remove,
    description: 'Delete a role by ID (soft delete)',
    database: {
      tables: ['roles', 'role_permissions', 'users'],
      mainTable: 'roles',
      sideEffects: [
        'Deletes associated role_permissions',
        'Check for users with this role before deletion'
      ]
    },
    sampleResponse: {
      status: true,
      message: 'deleted',
      data: null
    },
    examples: [
      {
        title: 'Delete role',
        description: 'Remove a role from the system',
        url: '/api/roles/delete/10',
        method: 'DELETE',
        response: {
          status: true,
          message: 'deleted',
          data: null
        }
      }
    ]
  },
  // --- Role Menus ---
  {
    path: '/menus',
    method: 'GET',
    middlewares: [verifyToken],
    handler: menuController.list,
    description: 'Get all available menu items',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      fields: {
        role_menus: ['id', 'title', 'path', 'icon', 'parent_id', 'sort_order', 'is_active']
      }
    },
    sampleResponse: {
      success: true,
      data: [
        {
          id: 1,
          title: 'Sales',
          path: '/sales',
          icon: 'shopping-cart',
          children: []
        }
      ]
    },
    examples: [
      {
        title: 'List all menu items',
        description: 'Get a hierarchical list of all menu items',
        url: '/api/roles/menus',
        method: 'GET',
        response: {
          success: true,
          data: [
            { id: 1, title: 'Dashboard', path: '/dashboard', icon: 'home', children: [] },
            { id: 2, title: 'Sales', path: '/sales', icon: 'shopping-cart', children: [] }
          ]
        }
      }
    ]
  },
  {
    path: '/menus',
    method: 'POST',
    middlewares: [verifyToken, validate(createMenuSchema)],
    handler: handlerWithFields(menuController.create, createMenuSchema),
    description: 'Create a new menu item',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      requiredFields: ['title'],
      optionalFields: ['path', 'icon', 'parent_id', 'sort_order', 'is_active'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at']
    },
    sampleRequest: {
      title: 'Products',
      path: '/products',
      icon: 'box',
      sort_order: 2
    },
    sampleResponse: {
      status: true,
      message: 'Menu item created successfully'
    },
    examples: [
      {
        title: 'Create menu item',
        description: 'Add a new item to the navigation menu',
        url: '/api/roles/menus',
        method: 'POST',
        request: {
          title: 'Reports',
          path: '/reports',
          icon: 'bar-chart',
          sort_order: 3
        },
        response: {
          status: true,
          message: 'Menu item created successfully'
        }
      }
    ]
  },
  {
    path: '/menus/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: menuController.get,
    description: 'Get menu item by ID',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus'
    },
    sampleResponse: {
      success: true,
      data: {
        id: 1,
        title: 'Sales'
      }
    },
    examples: [
      {
        title: 'Get menu item',
        description: 'Retrieve details of a specific menu item',
        url: '/api/roles/menus/1',
        method: 'GET',
        response: {
          success: true,
          data: { id: 1, title: 'Dashboard', path: '/dashboard', icon: 'home' }
        }
      }
    ]
  },
  {
    path: '/menus/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateMenuSchema)],
    handler: handlerWithFields(menuController.update, updateMenuSchema),
    description: 'Update menu item by ID',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      updatableFields: ['title', 'path', 'icon', 'parent_id', 'sort_order', 'is_active']
    },
    sampleRequest: {
      title: 'Sales & Orders'
    },
    sampleResponse: {
      status: true,
      message: 'Menu item updated successfully'
    },
    examples: [
      {
        title: 'Update menu item',
        description: 'Modify an existing menu item',
        url: '/api/roles/menus/1',
        method: 'PUT',
        request: { title: 'Main Dashboard', icon: 'activity' },
        response: {
          status: true,
          message: 'Menu item updated successfully'
        }
      }
    ]
  },
  {
    path: '/menus/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: menuController.remove,
    description: 'Delete menu item by ID',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      sideEffects: ['Does not cascade delete children automatically (implementation dependent)']
    },
    sampleResponse: {
      status: true,
      message: 'Menu item deleted successfully'
    },
    examples: [
      {
        title: 'Delete menu item',
        description: 'Remove a menu item',
        url: '/api/roles/menus/3',
        method: 'DELETE',
        response: {
          status: true,
          message: 'Menu item deleted successfully'
        }
      }
    ]
  },
  // --- Role Dashboards ---
  {
    path: '/dashboards',
    method: 'GET',
    middlewares: [verifyToken],
    handler: dashboardController.list,
    description: 'Get all available dashboard widgets',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards',
      fields: {
        role_dashboards: ['id', 'name', 'slug', 'type', 'size', 'is_active']
      }
    },
    sampleResponse: {
      success: true,
      data: [
        {
          id: 1,
          name: 'Total Revenue',
          slug: 'total-revenue',
          type: 'stat',
          size: '1x1'
        }
      ]
    },
    examples: [
      {
        title: 'List dashboard widgets',
        description: 'Get all available dashboard widgets',
        url: '/api/roles/dashboards',
        method: 'GET',
        response: {
          success: true,
          data: [
            { id: 1, name: 'Sales Overview', slug: 'sales-overview', type: 'chart' }
          ]
        }
      }
    ]
  },
  {
    path: '/dashboards',
    method: 'POST',
    middlewares: [verifyToken, validate(createDashboardSchema)],
    handler: handlerWithFields(dashboardController.create, createDashboardSchema),
    description: 'Create a new dashboard widget definition',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards',
      requiredFields: ['name', 'slug'],
      optionalFields: ['type', 'size', 'is_active'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at']
    },
    sampleRequest: {
      name: 'Monthly Sales Chart',
      slug: 'monthly-sales-chart',
      type: 'chart',
      size: '2x1'
    },
    sampleResponse: {
      status: true,
      message: 'Dashboard widget created successfully'
    },
    examples: [
      {
        title: 'Create dashboard widget',
        description: 'Register a new dashboard widget',
        url: '/api/roles/dashboards',
        method: 'POST',
        request: {
          name: 'New Customers',
          slug: 'new-customers-stat',
          type: 'stat',
          size: '1x1'
        },
        response: {
          status: true,
          message: 'Dashboard widget created successfully'
        }
      }
    ]
  },
  {
    path: '/dashboards/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: dashboardController.get,
    description: 'Get dashboard widget by ID',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards'
    },
    sampleResponse: {
      success: true,
      data: {
        id: 1,
        name: 'Total Revenue'
      }
    },
    examples: [
      {
        title: 'Get widget details',
        description: 'Retrieve details of a specific widget',
        url: '/api/roles/dashboards/1',
        method: 'GET',
        response: {
          success: true,
          data: { id: 1, name: 'Sales Overview', slug: 'sales-overview' }
        }
      }
    ]
  },
  {
    path: '/dashboards/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateDashboardSchema)],
    handler: handlerWithFields(dashboardController.update, updateDashboardSchema),
    description: 'Update dashboard widget by ID',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards',
      updatableFields: ['name', 'slug', 'type', 'size', 'is_active']
    },
    sampleRequest: {
      size: '2x2'
    },
    sampleResponse: {
      status: true,
      message: 'Dashboard widget updated successfully'
    },
    examples: [
      {
        title: 'Update widget',
        description: 'Modify a dashboard widget',
        url: '/api/roles/dashboards/1',
        method: 'PUT',
        request: { size: '2x1' },
        response: {
          status: true,
          message: 'Dashboard widget updated successfully'
        }
      }
    ]
  },
  {
    path: '/dashboards/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: dashboardController.remove,
    description: 'Delete dashboard widget by ID',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards'
    },
    sampleResponse: {
      status: true,
      message: 'Dashboard widget deleted successfully'
    },
    examples: [
      {
        title: 'Delete widget',
        description: 'Remove a dashboard widget',
        url: '/api/roles/dashboards/2',
        method: 'DELETE',
        response: {
          status: true,
          message: 'Dashboard widget deleted successfully'
        }
      }
    ]
  }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
  router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
