const express = require('express');
const router = express.Router();
const controller = require('./role.controller');
const validate = require('../../core/middleware/validate');
const { verifyToken } = require('../../core/middleware/auth');
const { createSchema, updateSchema } = require('./role.validation');
const { handlerWithFields } = require('../../core/utils/zodTypeView');

// Module name for routes-tree grouping
router.moduleName = 'Roles';

// Define routes metadata with comprehensive documentation
router.routesMeta = [
  {
    path: '/add',
    method: 'POST',
    middlewares: [verifyToken, validate(createSchema)],
    handler: handlerWithFields(controller.create, createSchema),
    description: 'Create a new role with permissions',
    database: {
      tables: ['roles', 'role_permissions', 'permissions'],
      mainTable: 'roles',
      requiredFields: ['name'],
      optionalFields: ['description', 'permissions'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at'],
      relationships: [
        'role_permissions.role_id -> roles.id (FK)',
        'role_permissions.permission_id -> permissions.id (FK)'
      ],
      sideEffects: ['Creates role_permissions entries for each permission']
    },
    sampleRequest: {
      name: 'Sales Manager',
      description: 'Manages sales team and operations',
      permissions: [1, 2, 5, 10]
    },
    sampleResponse: {
      status: true,
      message: 'created',
      data: {
        id: 5,
        name: 'Sales Manager',
        description: 'Manages sales team and operations',
        created_at: '2025-12-02T10:00:00.000Z'
      }
    }
  },
  {
    path: '/update/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateSchema)],
    handler: handlerWithFields(controller.update, updateSchema),
    description: 'Update an existing role by ID',
    database: {
      tables: ['roles', 'role_permissions', 'permissions'],
      mainTable: 'roles',
      updatableFields: ['name', 'description', 'permissions'],
      readOnlyFields: ['id', 'created_at'],
      autoUpdatedFields: ['updated_at'],
      relationships: [
        'role_permissions.role_id -> roles.id (FK)',
        'role_permissions.permission_id -> permissions.id (FK)'
      ],
      sideEffects: ['Updates role_permissions entries']
    },
    sampleRequest: {
      name: 'Senior Sales Manager',
      description: 'Senior level sales management role',
      permissions: [1, 2, 5, 10, 15]
    },
    sampleResponse: {
      status: true,
      message: 'updated',
      data: {
        id: 5,
        name: 'Senior Sales Manager',
        description: 'Senior level sales management role',
        updated_at: '2025-12-02T10:05:00.000Z'
      }
    }
  },
  {
    path: '/list',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.list,
    description: 'Get paginated list of all roles',
    database: {
      tables: ['roles'],
      mainTable: 'roles',
      fields: {
        roles: ['id', 'name', 'description', 'created_at', 'updated_at']
      }
    },
    queryParams: {
      page: '1 (default)',
      limit: '10 (default)'
    },
    sampleResponse: {
      success: true,
      message: 'Roles retrieved successfully',
      pagination: {
        total: 5,
        page: '1',
        limit: '10',
        totalPage: 1
      },
      data: [
        {
          id: 1,
          name: 'Admin',
          description: 'Full system access',
          created_at: '2025-12-01T00:00:00.000Z'
        },
        {
          id: 2,
          name: 'Manager',
          description: 'Department management access',
          created_at: '2025-12-01T00:00:00.000Z'
        }
      ]
    }
  },
  {
    path: '/get/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.get,
    description: 'Get a specific role by ID with permissions',
    database: {
      tables: ['roles', 'role_permissions', 'permissions'],
      mainTable: 'roles',
      fields: {
        roles: ['id', 'name', 'description', 'created_at', 'updated_at'],
        permissions: ['id', 'name', 'slug', 'description']
      },
      relationships: [
        'role_permissions.role_id -> roles.id (FK)',
        'role_permissions.permission_id -> permissions.id (FK)'
      ]
    },
    sampleResponse: {
      status: true,
      message: 'user',
      data: {
        id: 1,
        name: 'Admin',
        description: 'Full system access',
        permissions: [
          { id: 1, name: 'users.create' },
          { id: 2, name: 'users.read' },
          { id: 3, name: 'users.update' }
        ],
        created_at: '2025-12-01T00:00:00.000Z'
      }
    }
  },
  {
    path: '/delete/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: controller.remove,
    description: 'Delete a role by ID (soft delete)',
    database: {
      tables: ['roles', 'role_permissions', 'users'],
      mainTable: 'roles',
      sideEffects: [
        'Deletes associated role_permissions',
        'Check for users with this role before deletion'
      ]
    },
    sampleResponse: {
      status: true,
      message: 'deleted',
      data: null
    }
  },
];

// Register routes from metadata
router.routesMeta.forEach(r => {
  router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
