const express = require('express');
const router = express.Router();
const controller = require('./role.controller');
const validate = require('../../core/middleware/validate');
const { verifyToken } = require('../../core/middleware/auth');
const { createSchema, updateSchema } = require('./role.validation');
const { createMenuSchema, updateMenuSchema } = require('./role_menu.validation');
const { createDashboardSchema, updateDashboardSchema } = require('./role_dashboard.validation');
const menuController = require('./role_menu.controller');
const dashboardController = require('./role_dashboard.controller');
const { handlerWithFields } = require('../../core/utils/zodTypeView');

// Module name for routes-tree grouping
router.moduleName = 'Roles';

// Define routes metadata with comprehensive documentation
router.routesMeta = [
  {
    path: '/add',
    method: 'POST',
    middlewares: [verifyToken, validate(createSchema)],
    handler: handlerWithFields(controller.create, createSchema),
    description: 'Create a new role with settings',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      requiredFields: ['name'],
      optionalFields: ['menu', 'dashboard', 'custom'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at'],
      relationships: [
        'role_settings.role_id -> roles.id (FK)'
      ],
      sideEffects: ['Creates role_settings entry']
    },
    sampleRequest: {
      role: 'Regional Sales Manager',
      display_name: 'Regional Sales Department Manager',
      description: 'Manages regional sales team and operations',
      status: 'active',
      permissions: ['sales.view', 'sales.create'],
      menu: ['sales', 'dashboard'],
      dashboard: ['overview', 'revenue'],
      custom: { theme: 'dark' }
    },
    sampleResponse: {
      status: true,
      message: 'created',
      data: {
        id: 5,
        role: 'Sales Manager',
        display_name: 'Sales Department Manager',
        description: 'Manages sales team and operations',
        status: 'active',
        permissions: ['sales.view', 'sales.create'],
        settings: {
          menu: ['sales', 'dashboard'],
          dashboard: ['overview', 'revenue'],
          custom: { theme: 'dark' }
        }
      }
    }
  },
  {
    path: '/update/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateSchema)],
    handler: handlerWithFields(controller.update, updateSchema),
    description: 'Update an existing role by ID',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      updatableFields: ['name', 'menu', 'dashboard', 'custom'],
      readOnlyFields: ['id', 'created_at'],
      autoUpdatedFields: ['updated_at'],
      relationships: [
        'role_settings.role_id -> roles.id (FK)'
      ],
      sideEffects: ['Updates role_settings entry']
    },
    sampleRequest: {
      name: 'Senior Sales Manager',
      menu: ['sales', 'dashboard', 'reports'],
      dashboard: ['overview', 'revenue', 'analytics'],
      custom: { theme: 'light' }
    },
    sampleResponse: {
      status: true,
      message: 'updated',
      data: {
        id: 5,
        name: 'Senior Sales Manager',
        settings: {
          menu: ['sales', 'dashboard', 'reports'],
          dashboard: ['overview', 'revenue', 'analytics'],
          custom: { theme: 'light' }
        }
      }
    }
  },
  {
    path: '/list',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.list,
    description: 'Get paginated list of all roles',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      fields: {
        roles: ['id', 'name', 'created_at'],
        role_settings: ['menu', 'dashboard', 'custom']
      }
    },
    queryParams: {
      page: '1 (default)',
      limit: '10 (default)'
    },
    sampleResponse: {
      success: true,
      message: 'Roles retrieved successfully',
      pagination: {
        total: 5,
        page: '1',
        limit: '10',
        totalPage: 1
      },
      data: [
        {
          id: 1,
          role: 'Admin',
          display_name: 'System Administrator',
          description: 'Full system access',
          status: 'active',
          permissions: ['*'],
          settings: {
            menu: ['all'],
            dashboard: ['main'],
            custom: {}
          }
        }
      ]
    }
  },
  {
    path: '/get/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.get,
    description: 'Get a specific role by ID with settings',
    database: {
      tables: ['roles', 'role_settings'],
      mainTable: 'roles',
      fields: {
        roles: ['id', 'name', 'created_at'],
        role_settings: ['menu', 'dashboard', 'custom']
      },
      relationships: [
        'role_settings.role_id -> roles.id (FK)'
      ]
    },
    sampleResponse: {
      status: true,
      message: 'Role retrieved successfully',
      data: {
        id: 1,
        name: 'Admin',
        settings: {
          menu: ['all'],
          dashboard: ['main'],
          custom: {}
        }
      }
    }
  },
  {
    path: '/delete/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: controller.remove,
    description: 'Delete a role by ID (soft delete)',
    database: {
      tables: ['roles', 'role_permissions', 'users'],
      mainTable: 'roles',
      sideEffects: [
        'Deletes associated role_permissions',
        'Check for users with this role before deletion'
      ]
    },
    sampleResponse: {
      status: true,
      message: 'deleted',
      data: null
    }
  },
  // --- Role Menus ---
  {
    path: '/menus',
    method: 'GET',
    middlewares: [verifyToken],
    handler: menuController.list,
    description: 'Get all available menu items',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      fields: {
        role_menus: ['id', 'title', 'path', 'icon', 'parent_id', 'sort_order', 'is_active']
      }
    },
    sampleResponse: {
      success: true,
      data: [
        {
          id: 1,
          title: 'Sales',
          path: '/sales',
          icon: 'shopping-cart',
          children: []
        }
      ]
    }
  },
  {
    path: '/menus',
    method: 'POST',
    middlewares: [verifyToken, validate(createMenuSchema)],
    handler: handlerWithFields(menuController.create, createMenuSchema),
    description: 'Create a new menu item',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      requiredFields: ['title'],
      optionalFields: ['path', 'icon', 'parent_id', 'sort_order', 'is_active'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at']
    },
    sampleRequest: {
      title: 'Products',
      path: '/products',
      icon: 'box',
      sort_order: 2
    },
    sampleResponse: {
      status: true,
      message: 'Menu item created successfully'
    }
  },
  {
    path: '/menus/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: menuController.get,
    description: 'Get menu item by ID',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus'
    },
    sampleResponse: {
      success: true,
      data: {
        id: 1,
        title: 'Sales'
      }
    }
  },
  {
    path: '/menus/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateMenuSchema)],
    handler: handlerWithFields(menuController.update, updateMenuSchema),
    description: 'Update menu item by ID',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      updatableFields: ['title', 'path', 'icon', 'parent_id', 'sort_order', 'is_active']
    },
    sampleRequest: {
      title: 'Sales & Orders'
    },
    sampleResponse: {
      status: true,
      message: 'Menu item updated successfully'
    }
  },
  {
    path: '/menus/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: menuController.remove,
    description: 'Delete menu item by ID',
    database: {
      tables: ['role_menus'],
      mainTable: 'role_menus',
      sideEffects: ['Does not cascade delete children automatically (implementation dependent)']
    },
    sampleResponse: {
      status: true,
      message: 'Menu item deleted successfully'
    }
  },
  // --- Role Dashboards ---
  {
    path: '/dashboards',
    method: 'GET',
    middlewares: [verifyToken],
    handler: dashboardController.list,
    description: 'Get all available dashboard widgets',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards',
      fields: {
        role_dashboards: ['id', 'name', 'slug', 'type', 'size', 'is_active']
      }
    },
    sampleResponse: {
      success: true,
      data: [
        {
          id: 1,
          name: 'Total Revenue',
          slug: 'total-revenue',
          type: 'stat',
          size: '1x1'
        }
      ]
    }
  },
  {
    path: '/dashboards',
    method: 'POST',
    middlewares: [verifyToken, validate(createDashboardSchema)],
    handler: handlerWithFields(dashboardController.create, createDashboardSchema),
    description: 'Create a new dashboard widget definition',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards',
      requiredFields: ['name', 'slug'],
      optionalFields: ['type', 'size', 'is_active'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at']
    },
    sampleRequest: {
      name: 'Monthly Sales Chart',
      slug: 'monthly-sales-chart',
      type: 'chart',
      size: '2x1'
    },
    sampleResponse: {
      status: true,
      message: 'Dashboard widget created successfully'
    }
  },
  {
    path: '/dashboards/:id',
    method: 'GET',
    middlewares: [verifyToken],
    handler: dashboardController.get,
    description: 'Get dashboard widget by ID',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards'
    },
    sampleResponse: {
      success: true,
      data: {
        id: 1,
        name: 'Total Revenue'
      }
    }
  },
  {
    path: '/dashboards/:id',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateDashboardSchema)],
    handler: handlerWithFields(dashboardController.update, updateDashboardSchema),
    description: 'Update dashboard widget by ID',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards',
      updatableFields: ['name', 'slug', 'type', 'size', 'is_active']
    },
    sampleRequest: {
      size: '2x2'
    },
    sampleResponse: {
      status: true,
      message: 'Dashboard widget updated successfully'
    }
  },
  {
    path: '/dashboards/:id',
    method: 'DELETE',
    middlewares: [verifyToken],
    handler: dashboardController.remove,
    description: 'Delete dashboard widget by ID',
    database: {
      tables: ['role_dashboards'],
      mainTable: 'role_dashboards'
    },
    sampleResponse: {
      status: true,
      message: 'Dashboard widget deleted successfully'
    }
  }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
  router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
