const express = require('express');
const router = express.Router();
const rawMaterialsController = require('./raw-materials.controller');
const { verifyToken } = require('../../core/middleware/auth');
const validate = require('../../core/middleware/validate');
const { createSupplier, updateSupplier } = require('../suppliers/suppliers.validation');
// const { moduleCheck } = require('../../core/middleware/moduleCheck');

router.moduleName = 'Raw Materials';
router.use(verifyToken);
// router.use(moduleCheck('raw_materials'));

router.routesMeta = [
    // --- Raw Materials ---
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getAllRawMaterials(req, res),
        description: 'List all raw materials',
        database: {
            tables: ['products'],
            mainTable: 'products',
            fields: {
                products: ['id', 'name', 'sku', 'product_type', 'stock_quantity', 'cost', 'unit_id', 'created_at']
            },
            filters: { product_type: 'raw_material' }
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)',
            search: 'Search by name or SKU'
        },
        sampleResponse: {
            success: true,
            message: 'Raw materials retrieved successfully',
            pagination: { total: 45, page: 1, limit: 10 },
            data: [{ id: 10, name: 'Cotton Fabric', sku: 'RM-COTTON-001', product_type: 'raw_material', stock_quantity: 500, cost: 5.50 }]
        }
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.createRawMaterial(req, res),
        description: 'Create a new raw material',
        database: {
            tables: ['products'],
            requiredFields: ['name', 'sku', 'cost', 'unit_id'],
            autoGeneratedFields: ['product_type (raw_material)']
        },
        sampleRequest: {
            name: 'Elastic Band',
            sku: 'RM-ELASTIC-001',
            price: 0,
            cost: 5.50,
            stock_quantity: 1000,
            unit_id: 2
        },
        sampleResponse: {
            success: true,
            message: 'Raw material created successfully',
            data: { id: 11, name: 'Elastic Band', product_type: 'raw_material', stock_quantity: 1000 }
        }
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getRawMaterialById(req, res),
        description: 'Get details of a specific raw material',
        database: { mainTable: 'products' },
        sampleResponse: {
            success: true,
            data: { id: 10, name: 'Cotton Fabric', sku: 'RM-COTTON-001', product_type: 'raw_material', stock_quantity: 500, cost: 5.50 }
        }
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.updateRawMaterial(req, res),
        description: 'Update raw material details',
        sampleRequest: { cost: 6.00, stock_quantity: 1200 },
        sampleResponse: {
            success: true,
            message: 'Raw material updated successfully',
            data: { id: 10, cost: 6.00, stock_quantity: 1200 }
        }
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.deleteRawMaterial(req, res),
        description: 'Delete a raw material',
        sampleResponse: {
            success: true,
            message: 'Raw material deleted successfully'
        }
    },

    // --- Categories & Units ---
    {
        path: '/category',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getAllCategories(req, res),
        description: 'List all product categories',
        database: {
            tables: ['categories'],
            mainTable: 'categories',
            fields: { categories: ['id', 'name', 'description'] }
        },
        queryParams: { search: 'Search category name' },
        sampleResponse: {
            success: true,
            data: [{ id: 1, name: 'Textiles', description: 'Fabrics and cloth' }]
        }
    },
    {
        path: '/category',
        method: 'POST',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.createCategory(req, res),
        description: 'Create a new category',
        database: { requiredFields: ['name'] },
        sampleRequest: { name: 'Dyes', description: 'Industrial dyes' },
        sampleResponse: {
            success: true,
            message: 'Category created successfully',
            data: { id: 5, name: 'Dyes' }
        }
    },
    {
        path: '/category/:id',
        method: 'PUT',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.updateCategory(req, res),
        description: 'Update a category',
        sampleRequest: { name: 'Industrial Dyes' },
        sampleResponse: {
            success: true,
            message: 'Category updated successfully',
            data: { id: 5, name: 'Industrial Dyes' }
        }
    },
    {
        path: '/category/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.deleteCategory(req, res),
        description: 'Delete a category',
        sampleResponse: {
            success: true,
            message: 'Category deleted successfully'
        }
    },
    {
        path: '/unit',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getAllUnits(req, res),
        description: 'List all measurement units',
        database: {
            tables: ['units'],
            mainTable: 'units',
            fields: { units: ['id', 'name', 'symbol'] }
        },
        sampleResponse: {
            success: true,
            data: [{ id: 1, name: 'Meter', symbol: 'm' }]
        }
    },

    // --- Suppliers ---
    {
        path: '/supplier',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getAllSuppliers(req, res),
        description: 'List all suppliers (Raw Materials context)',
        database: {
            tables: ['suppliers'],
            mainTable: 'suppliers',
            fields: { suppliers: ['id', 'name', 'email', 'phone', 'address', 'status'] }
        },
        queryParams: {
            page: 'Page number',
            limit: 'Items per page',
            search: 'Search by name',
            status: 'Filter by status (active/inactive)'
        },
        sampleResponse: {
            success: true,
            data: [{ id: 1, name: 'Fabrics Ltd', email: 'contac@fabrics.com', status: 'active' }]
        }
    },
    {
        path: '/supplier',
        method: 'POST',
        middlewares: [validate(createSupplier)],
        handler: (req, res) => rawMaterialsController.createSupplier(req, res),
        description: 'Add a new supplier',
        database: { requiredFields: ['name', 'email'] },
        sampleRequest: { name: 'Fabric Supplies Co', email: 'sales@fabric.com', phone: '1234567890', address: '123 Textile Rd' },
        sampleResponse: {
            success: true,
            message: 'Supplier created successfully',
            data: { id: 2, name: 'Fabric Supplies Co' }
        }
    },
    {
        path: '/supplier/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getSupplierById(req, res),
        description: 'Get supplier details',
        sampleResponse: {
            success: true,
            data: { id: 1, name: 'Fabrics Ltd', email: 'contac@fabrics.com', phone: '1234567890', address: '123 Main St' }
        }
    },
    {
        path: '/supplier/:id',
        method: 'PUT',
        middlewares: [validate(updateSupplier)],
        handler: (req, res) => rawMaterialsController.updateSupplier(req, res),
        description: 'Update supplier details',
        sampleRequest: { phone: '0987654321', status: 'active' },
        sampleResponse: {
            success: true,
            message: 'Supplier updated successfully',
            data: { id: 1, phone: '0987654321' }
        }
    },
    {
        path: '/supplier/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.deleteSupplier(req, res),
        description: 'Remove a supplier',
        sampleResponse: {
            success: true,
            message: 'Supplier deleted successfully'
        }
    },

    // --- Purchase Orders ---
    {
        path: '/purchase-orders',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getPurchaseOrders(req, res),
        description: 'List all purchase orders',
        database: {
            tables: ['purchase_orders', 'suppliers'],
            mainTable: 'purchase_orders',
            fields: {
                purchase_orders: ['id', 'po_number', 'supplier_id', 'status', 'total_amount', 'order_date'],
                suppliers: ['id', 'name']
            }
        },
        queryParams: { page: '1', limit: '10', status: 'pending', supplier_id: '1' },
        sampleResponse: {
            success: true,
            data: [{ id: 101, po_number: 'PO-123456', status: 'pending', total_amount: 500.00 }]
        }
    },
    {
        path: '/purchase-orders',
        method: 'POST',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.createPurchaseOrder(req, res),
        description: 'Create a new purchase order',
        database: { requiredFields: ['supplier_id', 'items', 'expected_delivery_date'] },
        sampleRequest: {
            supplier_id: 1,
            items: [{ product_id: 10, quantity: 100, unit_cost: 5.00 }],
            order_date: '2026-01-10',
            expected_delivery_date: '2026-01-20',
            notes: 'Urgent delivery'
        },
        sampleResponse: {
            success: true,
            message: 'Purchase Order created',
            data: { id: 101, po_number: 'PO-123456', status: 'pending' }
        }
    },
    {
        path: '/purchase-orders/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getPurchaseOrderById(req, res),
        description: 'Get purchase order details',
        sampleResponse: {
            success: true,
            data: {
                id: 101,
                po_number: 'PO-123456',
                supplier_id: 1,
                status: 'pending',
                items: [{ product_id: 10, quantity: 100, unit_cost: 5.00, line_total: 500.00 }]
            }
        }
    },
    {
        path: '/purchase-orders/:id',
        method: 'PUT',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.updatePurchaseOrder(req, res),
        description: 'Update purchase order',
        sampleRequest: { status: 'approved' },
        sampleResponse: {
            success: true,
            message: 'Purchase order updated successfully',
            data: { id: 101, status: 'approved' }
        }
    },
    {
        path: '/purchase-orders/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.deletePurchaseOrder(req, res),
        description: 'Cancel/Delete a purchase order',
        sampleResponse: {
            success: true,
            message: 'Purchase order deleted successfully'
        }
    },

    // --- Invoices ---
    {
        path: '/purchase-orders/invoice',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getInvoices(req, res),
        description: 'List all procurement invoices',
        database: { mainTable: 'purchase_invoices' },
        sampleResponse: {
            success: true,
            data: [{ id: 1, invoice_number: 'INV-SUP-001', total_amount: 500.00, status: 'unpaid' }]
        }
    },
    {
        path: '/purchase-orders/invoice',
        method: 'POST',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.createInvoice(req, res),
        description: 'Record a new invoice',
        database: { requiredFields: ['purchase_order_id', 'invoice_date', 'due_date'] },
        sampleRequest: { purchase_order_id: 5, invoice_date: '2026-01-22', due_date: '2026-02-22', invoice_number: 'INV-SUP-001' },
        sampleResponse: {
            success: true,
            message: 'Invoice created successfully',
            data: { id: 2, invoice_number: 'INV-SUP-001' }
        }
    },
    {
        path: '/purchase-orders/invoice/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getInvoiceById(req, res),
        description: 'Get invoice details',
        sampleResponse: {
            success: true,
            data: { id: 1, invoice_number: 'INV-SUP-001', total_amount: 500.00, due_date: '2026-02-22', status: 'unpaid' }
        }
    },
    {
        path: '/purchase-orders/invoice/:id',
        method: 'PUT',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.updateInvoice(req, res),
        description: 'Update invoice details',
        sampleRequest: { status: 'paid', paid_amount: 500.00 },
        sampleResponse: {
            success: true,
            message: 'Invoice updated successfully',
            data: { id: 1, status: 'paid' }
        }
    },
    {
        path: '/purchase-orders/invoice/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.deleteInvoice(req, res),
        description: 'Delete an invoice',
        sampleResponse: {
            success: true,
            message: 'Invoice deleted successfully'
        }
    },

    // --- Payments ---
    {
        path: '/purchase-orders/payments',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getPayments(req, res),
        description: 'List all payments',
        database: { mainTable: 'purchase_payments' },
        sampleResponse: {
            success: true,
            data: [{ id: 1, amount: 500.00, payment_method: 'bank_transfer', status: 'completed' }]
        }
    },
    {
        path: '/purchase-orders/payments',
        method: 'POST',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.createPayment(req, res),
        description: 'Record a payment',
        database: { requiredFields: ['purchase_order_id', 'amount', 'payment_method'] },
        sampleRequest: { purchase_order_id: 5, amount: 500.00, payment_method: 'bank_transfer', paid_at: '2026-01-25', transaction_id: 'TXN12345678' },
        sampleResponse: {
            success: true,
            message: 'Payment recorded successfully',
            data: { id: 3, amount: 500.00, status: 'completed' }
        }
    },
    {
        path: '/purchase-orders/payments/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.getPaymentById(req, res),
        description: 'Get payment details',
        sampleResponse: {
            success: true,
            data: { id: 1, amount: 500.00, payment_method: 'bank_transfer', transaction_id: 'TXN12345678', date: '2026-01-25' }
        }
    },
    {
        path: '/purchase-orders/payments/:id',
        method: 'PUT',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.updatePayment(req, res),
        description: 'Update payment record',
        sampleRequest: { notes: 'Updated transaction reference' },
        sampleResponse: {
            success: true,
            message: 'Payment updated successfully'
        }
    },
    {
        path: '/purchase-orders/payments/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => rawMaterialsController.deletePayment(req, res),
        description: 'Void/Delete a payment',
        sampleResponse: {
            success: true,
            message: 'Payment voided/deleted successfully'
        }
    }
];

// Register routes
// Special handling to avoid /:id colliding with /supplier, /purchase-orders etc.
// In Express, specific routes must be defined BEFORE parameterized routes.
// The array order matters for our manual implementation, but here we are using standard routing.
// Express evaluates routes in definition order.
// We must ensure /supplier... comes before /:id.

const sortedRoutes = router.routesMeta.sort((a, b) => {
    // Basic heuristic: paths with dynamic :id should come last
    const aIsDynamic = a.path.includes(':');
    const bIsDynamic = b.path.includes(':');
    if (aIsDynamic && !bIsDynamic) return 1;
    if (!aIsDynamic && bIsDynamic) return -1;
    // Further sort by length (longer specific paths first)
    return b.path.length - a.path.length;
});


sortedRoutes.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
