const express = require('express');
const router = express.Router();
const controller = require('./auth.controller');
const validate = require('../../core/middleware/validate');
const { verifyToken } = require('../../core/middleware/auth');
const { loginSchema, registerSchema, refreshSchema, updateProfileSchema } = require('./auth.validation');
const { handlerWithFields } = require('../../core/utils/zodTypeView');

// Module name for routes-tree grouping
router.moduleName = 'Auth';

// Define routes metadata with comprehensive documentation
router.routesMeta = [
  {
    path: '/login',
    method: 'POST',
    middlewares: [validate(loginSchema)],
    handler: handlerWithFields(controller.login, loginSchema),
    description: 'Authenticate user and get access token',
    database: {
      tables: ['users', 'roles', 'role_settings', 'role_menus', 'role_dashboards'],
      mainTable: 'users',
      requiredFields: ['email', 'password'],
      relationships: [
        'users.role_id -> roles.id (FK)',
        'roles.id -> role_settings.role_id (FK)',
        'role_menus.parent_id -> role_menus.id (Self-referencing FK)'
      ],
      sideEffects: ['Generates JWT token']
    },
    sampleRequest: {
      email: 'admin@example.com',
      password: 'SecurePassword123!'
    },
    sampleResponse: {
      status: true,
      message: 'Login successful',
      data: {
        user: {
          id: 1,
          name: 'Admin User',
          email: 'admin@example.com',
          role_id: 1,
          created_at: '2025-01-01T00:00:00.000Z',
          role: {
            id: 1,
            name: 'admin',
            display_name: 'Administrator',
            description: 'Full system access',
            status: 'active',
            permissions: ['users.create', 'users.read', 'users.update', 'users.delete'],
            created_at: '2025-01-01T00:00:00.000Z',
            RoleSettings: {
              id: 1,
              role_id: 1,
              menu: null,
              dashboard: null,
              custom: null
            }
          }
        },
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        menus: [],
        dashboards: []
      }
    },
    examples: [
      {
        title: 'User Login',
        description: 'Authenticate a user with email and password to receive an access token.',
        url: '/api/auth/login',
        method: 'POST',
        request: {
          email: 'admin@example.com',
          password: 'SecurePassword123!'
        },
        response: {
          status: true,
          message: 'Login successful',
          data: {
            user: { id: 1, name: 'Admin User', email: 'admin@example.com', role_id: 1 },
            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            menus: [],
            dashboards: []
          }
        }
      }
    ]
  },
  {
    path: '/register',
    method: 'POST',
    middlewares: [validate(registerSchema)],
    handler: handlerWithFields(controller.register, registerSchema),
    description: 'Register a new user account',
    database: {
      tables: ['users', 'roles'],
      mainTable: 'users',
      requiredFields: ['name', 'email', 'password', 'role_id'],
      autoGeneratedFields: ['id', 'created_at', 'updated_at'],
      relationships: ['users.role_id -> roles.id (FK)']
    },
    sampleRequest: {
      name: 'John Doe',
      email: 'john.doe@example.com',
      password: 'SecurePassword123!',
      role_id: 2
    },
    sampleResponse: {
      status: true,
      message: 'Registration successful',
      data: {
        user: {
          id: 25,
          name: 'John Doe',
          email: 'john.doe@example.com',
          role_id: 2,
          created_at: '2025-12-02T10:00:00.000Z'
        },
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        expiresIn: 3600
      },
      code: 201
    },
    examples: [
      {
        title: 'User Registration',
        description: 'Register a new user account.',
        url: '/api/auth/register',
        method: 'POST',
        request: {
          name: 'John Doe',
          email: 'john.doe@example.com',
          password: 'SecurePassword123!',
          role_id: 2
        },
        response: {
          status: true,
          message: 'Registration successful',
          data: {
            user: { id: 25, name: 'John Doe', email: 'john.doe@example.com' },
            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            expiresIn: 3600
          },
          code: 201
        }
      }
    ]
  },
  {
    path: '/me',
    method: 'GET',
    middlewares: [verifyToken],
    handler: controller.me,
    description: 'Get current authenticated user information',
    database: {
      tables: ['users', 'roles', 'role_settings', 'role_menus', 'role_dashboards'],
      mainTable: 'users',
      fields: {
        users: ['id', 'name', 'email', 'role_id', 'created_at'],
        roles: ['id', 'name', 'display_name', 'description', 'status', 'permissions', 'created_at'],
        role_settings: ['id', 'role_id', 'menu', 'dashboard', 'custom'],
        role_menus: ['id', 'title', 'icon', 'path', 'parent_id', 'sort_order', 'is_active'],
        role_dashboards: ['id', 'name', 'slug', 'type', 'size', 'is_active']
      },
      relationships: [
        'users.role_id -> roles.id (FK)',
        'roles.id -> role_settings.role_id (FK)',
        'role_menus.parent_id -> role_menus.id (Self-referencing FK)'
      ]
    },
    sampleResponse: {
      status: true,
      message: 'User retrieved successfully',
      data: {
        user: {
          id: 1,
          name: 'Admin User',
          email: 'admin@example.com',
          phone: '+1234567890',
          profile_image: 'https://example.com/avatar.jpg',
          role_id: 1,
          created_at: '2025-01-01T00:00:00.000Z',
          role: {
            id: 1,
            name: 'admin',
            display_name: 'Administrator',
            description: 'Full system access',
            status: 'active',
            permissions: ['users.create', 'users.read', 'users.update', 'users.delete'],
            created_at: '2025-01-01T00:00:00.000Z',
            RoleSettings: {
              id: 1,
              role_id: 1,
              menu: null,
              dashboard: null,
              custom: null
            }
          }
        },
        menus: [],
        dashboards: []
      }
    },
    examples: [
      {
        title: 'Get Current User',
        description: 'Retrieve details of the currently authenticated user.',
        url: '/api/auth/me',
        method: 'GET',
        response: {
          status: true,
          message: 'User retrieved successfully',
          data: {
            user: {
              id: 1,
              name: 'Admin User',
              email: 'admin@example.com',
              phone: '+1234567890',
              profile_image: 'https://example.com/avatar.jpg'
            },
            menus: [],
            dashboards: []
          }
        }
      }
    ]
  },
  {
    path: '/refresh',
    method: 'POST',
    middlewares: [validate(refreshSchema)],
    handler: handlerWithFields(controller.refresh, refreshSchema),
    description: 'Refresh access token using refresh token',
    sampleRequest: {
      refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
    },
    sampleResponse: {
      status: true,
      message: 'Token refreshed successfully',
      data: {
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        expiresIn: 3600
      }
    },
    examples: [
      {
        title: 'Refresh Token',
        description: 'Obtain a new access token using a valid refresh token.',
        url: '/api/auth/refresh',
        method: 'POST',
        request: {
          refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        },
        response: {
          status: true,
          message: 'Token refreshed successfully',
          data: {
            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            expiresIn: 3600
          }
        }
      }
    ]
  },
  {
    path: '/logout',
    method: 'POST',
    middlewares: [verifyToken],
    handler: controller.logout,
    description: 'Logout user and invalidate tokens',
    sampleResponse: {
      status: true,
      message: 'Logout successful',
      data: null
    },
    examples: [
      {
        title: 'Logout',
        description: 'Invalidate the current user session.',
        url: '/api/auth/logout',
        method: 'POST',
        response: {
          status: true,
          message: 'Logout successful',
          data: null
        }
      }
    ]
  },
  {
    path: '/profile',
    method: 'PUT',
    middlewares: [verifyToken, validate(updateProfileSchema)],
    handler: handlerWithFields(controller.updateProfile, updateProfileSchema),
    description: 'Update current user profile',
    database: {
      tables: ['users', 'staffs'],
      mainTable: 'users/staffs',
      optionalFields: ['first_name', 'last_name', 'phone', 'position', 'address', 'city', 'state', 'country', 'postal_code', 'thumb_url']
    },
    sampleRequest: {
      first_name: 'John',
      last_name: 'Doe',
      phone: '+1234567890',
      city: 'New York'
    },
    sampleResponse: {
      status: true,
      message: 'Profile updated successfully',
      data: {
        id: 1,
        first_name: 'John',
        last_name: 'Doe',
        email: 'john@example.com',
        phone: '+1234567890',
        profile_image: 'https://example.com/new-avatar.jpg',
        city: 'New York',
        role_id: 2
      }
    },
    examples: [
      {
        title: 'Update Profile',
        description: 'Update user profile information',
        url: '/api/auth/profile',
        method: 'PUT',
        request: {
          first_name: 'John',
          last_name: 'Doe',
          phone: '+1234567890',
          profile_image: 'https://example.com/new-avatar.jpg'
        },
        response: {
          status: true,
          message: 'Profile updated successfully',
          data: {
            id: 1,
            first_name: 'John',
            last_name: 'Doe',
            email: 'john@example.com',
            phone: '+1234567890',
            profile_image: 'https://example.com/new-avatar.jpg'
          }
        }
      }
    ]
  }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
  router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
