const express = require('express');
const router = express.Router();
const staffsController = require('./staffs.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createStaff, updateStaff } = require('./staffs.validation');

// Module name for routes-tree grouping
router.moduleName = 'Staffs';

router.use(verifyToken);
router.use(moduleCheck('staffs'));

// Define routes metadata with comprehensive documentation
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => staffsController.getAllStaffs(req, res),
        description: 'Get all staff members with pagination',
        database: {
            tables: ['users', 'departments', 'roles'],
            mainTable: 'users',
            fields: {
                staffs: ['id', 'first_name', 'last_name', 'email', 'phone', 'position', 'department_id', 'role_id', 'hire_date', 'salary', 'address', 'city', 'status', 'thumb_url', 'gallery_items', 'created_at', 'updated_at'],
                departments: ['id', 'name'],
                roles: ['id', 'name', 'display_name']
            },
            relationships: ['staffs.department_id -> departments.id (FK)', 'staffs.role_id -> roles.id (FK)']
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)',
            status: 'Filter by status (active/inactive/terminated/on_leave)',
            department_id: 'Filter by department ID',
            role_id: 'Filter by role ID',
            search: 'Search by name, email, or position'
        },
        sampleResponse: {
            success: true,
            message: 'Staff members retrieved successfully',
            pagination: {
                total: 5,
                page: '1',
                limit: '10',
                totalPage: 1
            },
            data: [
                {
                    id: 1,
                    first_name: 'Michael',
                    last_name: 'Johnson',
                    email: 'michael.j@company.com',
                    phone: '+6666666666',
                    position: 'Sales Manager',
                    department_id: 1,
                    role_id: 2,
                    department: {
                        id: 1,
                        name: 'Sales',
                        description: 'Sales Department'
                    },
                    role: {
                        id: 2,
                        name: 'sales_manager',
                        display_name: 'Sales Manager'
                    },
                    status: 'active',
                    thumb_url: 'https://example.com/images/staff/michael.jpg',
                    gallery_items: [
                        'https://example.com/images/gallery/img1.jpg',
                        'https://example.com/images/gallery/img2.jpg'
                    ],
                    created_at: '2025-12-03T05:00:00.000Z'
                }
            ]
        },
        examples: [
            {
                title: 'Get all staff',
                description: 'Retrieve a list of all staff members',
                url: '/api/staffs?page=1&limit=10',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Staff members retrieved successfully',
                    pagination: { total: 5, page: '1', limit: '10', totalPage: 1 },
                    data: [
                        {
                            id: 1,
                            first_name: 'Michael',
                            last_name: 'Johnson',
                            position: 'Sales Manager',
                            status: 'active'
                        }
                    ]
                }
            }
        ]
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [validate(createStaff)],
        handler: handlerWithFields((req, res) => staffsController.createStaff(req, res), createStaff),
        description: 'Add a new staff member',
        database: {
            tables: ['users'],
            mainTable: 'users',
            requiredFields: ['first_name', 'last_name', 'email'],
            optionalFields: ['password', 'phone', 'position', 'department_id', 'role_id', 'hire_date', 'salary', 'address', 'city', 'status', 'thumb_url', 'gallery_items'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            first_name: 'Jane',
            last_name: 'Smith',
            email: 'jane.smith@example.com',
            password: 'securePassword123',
            phone: '+1987654321',
            position: 'Sales Representative',
            department_id: 1,
            role_id: 2,
            hire_date: '2025-01-15',
            salary: 50000.00,
            status: 'active',
            thumb_url: 'https://example.com/images/staff/jane.jpg',
            gallery_items: [
                'https://example.com/images/gallery/jane1.jpg',
                'https://example.com/images/gallery/jane2.jpg'
            ]
        },
        sampleResponse: {
            status: true,
            message: 'Staff member created successfully',
            data: {
                id: 2,
                first_name: 'Jane',
                last_name: 'Smith',
                email: 'jane.smith@example.com',
                thumb_url: 'https://example.com/images/staff/jane.jpg',
                gallery_items: [
                    'https://example.com/images/gallery/jane1.jpg',
                    'https://example.com/images/gallery/jane2.jpg'
                ],
                created_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Create new staff',
                description: 'Add a new employee to the system',
                url: '/api/staffs',
                method: 'POST',
                request: {
                    first_name: 'Jane',
                    last_name: 'Smith',
                    email: 'jane.smith@example.com',
                    position: 'Sales Rep',
                    role_id: 2,
                    hire_date: '2025-01-15'
                },
                response: {
                    status: true,
                    message: 'Staff member created successfully',
                    data: { id: 2, first_name: 'Jane', last_name: 'Smith' }
                }
            }
        ]
    },
    {
        path: '/routes',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => staffsController.getStaffRoutes(req, res),
        description: 'Get staff wise route assignments and stats',
        database: {
            tables: ['users', 'sales_routes', 'customers', 'orders'],
            mainTable: 'users',
            relationships: ['staffs <-> sales_routes', 'sales_routes -> customers', 'customers -> orders']
        },
        queryParams: {
            search: 'Search by staff name'
        },
        sampleResponse: [
            {
                "id": 1000,
                "name": "Staff Member 1",
                "role": "Sales Representative",
                "email": "staff1@example.com",
                "phone": "+8801700000000",
                "active": false,
                "routes": [
                    { "id": 1, "name": "Dhaka North - Sector 1", "status": "Active", "orders": 42 }
                ],
                "stats": {
                    "completedOrders": 834,
                    "rating": 4.6
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => staffsController.getStaffById(req, res),
        description: 'Get staff details',
        database: {
            tables: ['users', 'departments'],
            mainTable: 'users',
            fields: {
                staffs: ['id', 'first_name', 'last_name', 'email', 'phone', 'position', 'department_id', 'role_id', 'hire_date', 'salary', 'address', 'city', 'status', 'thumb_url', 'gallery_items', 'created_at', 'updated_at'],
                departments: ['id', 'name']
            },
            relationships: ['staffs.department_id -> departments.id (FK)']
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                first_name: 'John',
                last_name: 'Doe',
                email: 'john.doe@example.com',
                phone: '+1234567890',
                position: 'Manager',
                department_id: 1,
                role_id: 2,
                department: {
                    id: 1,
                    name: 'Sales',
                    description: 'Sales Department'
                },
                hire_date: '2024-01-01',
                salary: 75000.00,
                address: '123 Main St',
                city: 'New York',
                status: 'active',
                thumb_url: 'https://example.com/images/staff/john.jpg',
                gallery_items: [
                    'https://example.com/images/gallery/john1.jpg',
                    'https://example.com/images/gallery/john2.jpg',
                    'https://example.com/images/gallery/john3.jpg'
                ],
                created_at: '2025-12-02T10:00:00.000Z',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Get staff details',
                description: 'Retrieve detailed information for a specific staff member',
                url: '/api/staffs/1',
                method: 'GET',
                response: {
                    status: true,
                    data: {
                        id: 1,
                        first_name: 'John',
                        last_name: 'Doe',
                        position: 'Manager',
                        email: 'john.doe@example.com',
                        status: 'active'
                    }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updateStaff)],
        handler: handlerWithFields((req, res) => staffsController.updateStaff(req, res), updateStaff),
        description: 'Update staff details',
        database: {
            tables: ['users'],
            mainTable: 'users',
            updatableFields: ['first_name', 'last_name', 'email', 'password', 'phone', 'position', 'department_id', 'role_id', 'salary', 'address', 'city', 'status', 'thumb_url', 'gallery_items'],
            readOnlyFields: ['id', 'hire_date', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            position: 'Senior Manager',
            salary: 85000.00,
            password: 'newPassword123'
        },
        sampleResponse: {
            status: true,
            message: 'Staff member updated successfully',
            data: {
                id: 1,
                first_name: 'John',
                last_name: 'Doe',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Update staff details',
                description: 'Update the position or salary of a staff member',
                url: '/api/staffs/1',
                method: 'PUT',
                request: { position: 'Senior Manager', salary: 85000.00 },
                response: {
                    status: true,
                    message: 'Staff member updated successfully',
                    data: { id: 1, first_name: 'John', last_name: 'Doe', updated_at: '2025-12-02T10:00:00.000Z' }
                }
            },
            {
                title: 'Update staff password',
                description: 'Change a staff member\'s password',
                url: '/api/staffs/1',
                method: 'PUT',
                request: { password: 'newSecurePassword456' },
                response: {
                    status: true,
                    message: 'Staff member updated successfully',
                    data: { id: 1, first_name: 'John', last_name: 'Doe', updated_at: '2025-12-02T10:00:00.000Z' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => staffsController.deleteStaff(req, res),
        description: 'Remove a staff member',
        database: {
            tables: ['users', 'attendance'],
            mainTable: 'users',
            sideEffects: ['May affect attendance records']
        },
        sampleResponse: {
            status: true,
            message: 'Staff member deleted successfully'
        },
        examples: [
            {
                title: 'Delete staff',
                description: 'Remove a staff member from the system',
                url: '/api/staffs/1',
                method: 'DELETE',
                response: {
                    status: true,
                    message: 'Staff member deleted successfully'
                }
            }
        ]
    }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
