const express = require('express');
const router = express.Router();
const productsController = require('./products.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createProduct, updateProduct, createCategory, updateCategory, createUnit, updateUnit } = require('./products.validation');
const { updateStock } = require('./stock.validation');

// Module name for routes-tree grouping
router.moduleName = 'Products';

router.use(verifyToken);
router.use(moduleCheck('products'));

// Define routes metadata with comprehensive documentation
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getAllProducts(req, res),
        description: 'List all products',
        database: {
            tables: ['products', 'categories', 'units', 'product_images'],
            mainTable: 'products',
            fields: {
                products: ['id', 'name', 'sku', 'description', 'category_id', 'unit_id', 'price', 'cost', 'purchase_tax', 'sales_tax', 'stock_quantity', 'initial_stock', 'min_stock_level', 'max_stock_level', 'barcode', 'image_url', 'is_active', 'created_at', 'updated_at'],
                categories: ['id', 'name'],
                units: ['id', 'name', 'symbol'],
                product_images: ['id', 'product_id', 'image_url', 'sort_order']
            },
            relationships: [
                'products.category_id -> categories.id',
                'products.unit_id -> units.id',
                'product_images.product_id -> products.id'
            ]
        },
        queryParams: {
            category_id: 'Filter by category ID',
            is_active: 'Filter by active status (true/false)',
            search: 'Search by name, SKU, or barcode',
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Products retrieved successfully',
            pagination: {
                total: 50,
                page: '1',
                limit: '10',
                totalPage: 5
            },
            data: [
                {
                    id: 1,
                    name: 'Wireless Mouse',
                    sku: 'MOU-001',
                    description: 'Ergonomic wireless mouse',
                    category_id: 1,
                    unit_id: 1,
                    price: 29.99,
                    cost: 15.00,
                    stock_quantity: 100,
                    initial_stock: 100,
                    min_stock_level: 20,
                    max_stock_level: 200,
                    barcode: '9876543210987',
                    thumb_url: 'http://example.com/thumb.jpg',
                    is_active: true,
                    category: {
                        id: 1,
                        name: 'Electronics'
                    },
                    unit: {
                        id: 1,
                        name: 'Piece',
                        symbol: 'pcs'
                    },
                    gallery_items: [
                        "http://example.com/img1.jpg",
                        "http://example.com/img2.jpg"
                    ]
                }
            ]
        },
        examples: [
            {
                title: 'List Products',
                description: 'Retrieve a paginated list of products with optional filters',
                url: '/api/products?page=1&limit=10&category_id=1',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Products retrieved successfully',
                    pagination: { total: 50, page: '1', limit: '10', totalPage: 5 },
                    data: [{ id: 1, name: 'Wireless Mouse', sku: 'MOU-001', price: 29.99, stock_quantity: 100 }]
                }
            }
        ]
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [validate(createProduct)],
        handler: handlerWithFields((req, res) => productsController.createProduct(req, res), createProduct),
        description: 'Add a new product',
        database: {
            tables: ['products', 'product_images'],
            mainTable: 'products',
            requiredFields: ['name', 'sku', 'price', 'category_id', 'unit_id'],
            optionalFields: ['description', 'cost', 'purchase_tax', 'sales_tax', 'stock_quantity', 'initial_stock', 'min_stock_level', 'max_stock_level', 'barcode', 'image_url', 'weight', 'length', 'width', 'height', 'is_active'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at'],
            relationships: [
                'products.category_id -> categories.id (FK)',
                'products.unit_id -> units.id (FK)',
                'product_images.product_id -> products.id (FK)'
            ]
        },
        sampleRequest: {
            name: 'Wireless Mouse',
            sku: 'MOU-001',
            description: 'Ergonomic wireless mouse',
            category_id: 1,
            unit_id: 1,
            price: 29.99,
            cost: 15.00,
            purchase_tax: 5.00,
            sales_tax: 10.00,
            stock_quantity: 100,
            initial_stock: 100,
            min_stock_level: 20,
            max_stock_level: 200,
            barcode: '9876543210987',
            weight: 0.15,
            length: 12.5,
            width: 7.0,
            height: 4.0,
            is_active: true,
            thumb_url: "http://example.com/thumb.jpg",
            gallery_items: [
                "http://example.com/img1.jpg",
                "http://example.com/img2.jpg"
            ]
        },
        sampleResponse: {
            status: true,
            message: 'Product created successfully',
            data: {
                id: 2,
                name: 'Wireless Mouse',
                sku: 'MOU-001',
                price: 29.99,
                created_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Create Product',
                description: 'Add a new product to the catalog',
                url: '/api/products',
                method: 'POST',
                request: {
                    name: 'Gaming Keyboard',
                    sku: 'KEY-002',
                    description: 'Mechanical RGB keyboard',
                    category_id: 1,
                    unit_id: 1,
                    price: 89.99,
                    cost: 50.00,
                    stock_quantity: 50,
                    initial_stock: 50,
                    min_stock_level: 10,
                    image_url: 'http://example.com/keyboard.jpg'
                },
                response: {
                    status: true,
                    message: 'Product created successfully',
                    data: { id: 2, name: 'Gaming Keyboard', sku: 'KEY-002', price: 89.99 }
                }
            }
        ]
    },
    {
        path: '/stats',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getProductStats(req, res),
        description: 'Get product statistics (Total, Active, Low Stock, Total Stock Quantity)',
        database: {
            tables: ['products'],
            mainTable: 'products',
            fields: {
                calculated: ['totalProducts', 'activeProducts', 'lowStock', 'totalStock']
            }
        },
        sampleResponse: {
            status: true,
            message: 'Product stats retrieved successfully',
            data: [
                {
                    label: "Total Products",
                    value: 150,
                    color: "bg-blue-600"
                }
            ]
        },
        examples: [
            {
                title: 'Get Product Stats',
                description: 'Retrieve statistical overview of products',
                url: '/api/products/stats',
                method: 'GET',
                response: {
                    status: true,
                    message: 'Product stats retrieved successfully',
                    data: [{ label: "Total Products", value: 150, color: "bg-blue-600" }]
                }
            }
        ]
    },
    {
        path: '/stock',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getStockDetails(req, res),
        description: 'Get stock management details',
        database: {
            tables: ['products'],
            mainTable: 'products',
            fields: {
                products: ['id', 'name', 'sku', 'stock_quantity', 'initial_stock', 'min_stock_level', 'price']
            }
        },
        sampleResponse: {
            status: true,
            data: {
                total_products: 150,
                low_stock_count: 5,
                total_stock_value: "45000.00",
                low_stock_products: [
                    {
                        id: 10,
                        name: "USB Cable",
                        sku: "USB-001",
                        stock_quantity: 5,
                        initial_stock: 50,
                        min_stock_level: 20,
                        price: 5.99
                    }
                ]
            }
        },
        examples: [
            {
                title: 'Get Stock Details',
                description: 'Get comprehensive stock details including low stock alerts',
                url: '/api/products/stock',
                method: 'GET',
                response: {
                    status: true,
                    data: {
                        total_products: 150,
                        low_stock_count: 5,
                        low_stock_products: [{ id: 10, name: "USB Cable", stock_quantity: 5, min_stock_level: 20 }]
                    }
                }
            }
        ]
    },
    {
        path: '/categories',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getAllCategories(req, res),
        description: 'List all categories',
        database: {
            tables: ['categories'],
            mainTable: 'categories',
            fields: {
                categories: ['id', 'name', 'description', 'parent_id', 'is_active', 'created_at', 'updated_at']
            },
            relationships: ['categories.parent_id -> categories.id (self-referencing)']
        },
        queryParams: {
            search: 'Search by category name or description',
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Categories retrieved successfully',
            pagination: {
                total: 2,
                page: '1',
                limit: '10',
                totalPage: 1
            },
            data: [
                {
                    id: 1,
                    name: 'Electronics',
                    description: 'Electronic devices and accessories',
                    parent_id: null,
                    is_active: true
                },
                {
                    id: 2,
                    name: 'Office Supplies',
                    description: 'Office and stationery items',
                    parent_id: null,
                    is_active: true
                }
            ]
        },
        examples: [
            {
                title: 'List Categories',
                description: 'Get all product categories',
                url: '/api/products/categories',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Categories retrieved successfully',
                    data: [{ id: 1, name: 'Electronics', parent_id: null }]
                }
            }
        ]
    },
    {
        path: '/units',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getAllUnits(req, res),
        description: 'List all units',
        database: {
            tables: ['units'],
            mainTable: 'units',
            fields: {
                units: ['id', 'name', 'symbol', 'description', 'is_active', 'created_at', 'updated_at']
            }
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Units retrieved successfully',
            pagination: {
                total: 3,
                page: '1',
                limit: '10',
                totalPage: 1
            },
            data: [
                {
                    id: 1,
                    name: 'Piece',
                    symbol: 'pcs',
                    is_active: true
                },
                {
                    id: 2,
                    name: 'Kilogram',
                    symbol: 'kg',
                    is_active: true
                },
                {
                    id: 3,
                    name: 'Liter',
                    symbol: 'L',
                    is_active: true
                }
            ]
        },
        examples: [
            {
                title: 'List Units',
                description: 'Get all measurement units',
                url: '/api/products/units',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Units retrieved successfully',
                    data: [{ id: 1, name: 'Piece', symbol: 'pcs' }]
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getProductById(req, res),
        description: 'Get a single product by ID',
        database: {
            tables: ['products', 'categories', 'units', 'product_images'],
            mainTable: 'products',
            fields: {
                products: ['id', 'name', 'sku', 'description', 'category_id', 'unit_id', 'price', 'cost', 'purchase_tax', 'sales_tax', 'stock_quantity', 'initial_stock', 'min_stock_level', 'max_stock_level', 'barcode', 'image_url', 'weight', 'length', 'width', 'height', 'is_active', 'created_at', 'updated_at'],
                categories: ['id', 'name', 'description'],
                units: ['id', 'name', 'symbol'],
                product_images: ['id', 'product_id', 'image_url', 'sort_order']
            },
            relationships: [
                'products.category_id -> categories.id (FK)',
                'products.unit_id -> units.id (FK)',
                'product_images.product_id -> products.id (FK)'
            ]
        },
        sampleResponse: {
            status: true,
            message: 'Product retrieved successfully',
            data: {
                id: 1,
                name: 'Laptop Computer',
                sku: 'LAP-001',
                description: 'High-performance laptop',
                category_id: 1,
                unit_id: 1,
                price: 999.99,
                cost: 750.00,
                purchase_tax: 5.00,
                sales_tax: 10.00,
                stock_quantity: 50,
                initial_stock: 100,
                min_stock_level: 10,
                max_stock_level: 100,
                barcode: '1234567890123',
                image_url: '/uploads/laptop.jpg',
                is_active: true,
                created_at: '2025-12-02T10:00:00.000Z',
                updated_at: '2025-12-02T10:00:00.000Z',
                category: {
                    id: 1,
                    name: 'Electronics',
                    description: 'Electronic devices and accessories'
                },
                unit: {
                    id: 1,
                    name: 'Piece',
                    symbol: 'pcs'
                }
            }
        },
        examples: [
            {
                title: 'Get Product',
                description: 'Get detailed information for a single product',
                url: '/api/products/1',
                method: 'GET',
                response: {
                    status: true,
                    message: 'Product retrieved successfully',
                    data: { id: 1, name: 'Wireless Mouse', sku: 'MOU-001' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updateProduct)],
        handler: handlerWithFields((req, res) => productsController.updateProduct(req, res), updateProduct),
        description: 'Update a product',
        database: {
            tables: ['products', 'product_images'],
            mainTable: 'products',
            updatableFields: ['name', 'sku', 'description', 'category_id', 'unit_id', 'price', 'cost', 'purchase_tax', 'sales_tax', 'stock_quantity', 'initial_stock', 'min_stock_level', 'max_stock_level', 'barcode', 'image_url', 'weight', 'is_active'],
            readOnlyFields: ['id', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            name: 'Wireless Mouse Pro',
            price: 34.99,
            stock_quantity: 150
        },
        sampleResponse: {
            status: true,
            message: 'Product updated successfully',
            data: {
                id: 2,
                name: 'Wireless Mouse Pro',
                price: 34.99,
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Update Product',
                description: 'Update product details',
                url: '/api/products/2',
                method: 'PUT',
                request: { name: 'Wireless Mouse Pro', price: 34.99 },
                response: {
                    status: true,
                    message: 'Product updated successfully',
                    data: { id: 2, name: 'Wireless Mouse Pro', price: 34.99 }
                }
            }
        ]
    },
    {
        path: '/:id/stock',
        method: 'PUT',
        middlewares: [validate(updateStock)],
        handler: handlerWithFields((req, res) => productsController.updateStock(req, res), updateStock),
        description: 'Update product stock quantity. Supports add, subtract, or set operations.',
        database: {
            tables: ['products', 'stock_movements'],
            mainTable: 'products',
            updatedFields: ['stock_quantity'],
            sideEffects: [
                'Creates stock_movements record',
                'Records movement_type (purchase/sale/adjustment)',
                'Stores quantity change (positive or negative)',
                'Links to reference (order, purchase_order, or manual)'
            ]
        },
        sampleRequest: {
            operation: 'add',
            quantity: 50
        },
        sampleResponse: {
            status: true,
            message: 'Stock updated successfully',
            data: {
                id: 1,
                name: 'Wireless Mouse',
                sku: 'MOU-001',
                stock_quantity: 150,
                initial_stock: 100,
                thumb_url: 'http://example.com/thumb.jpg',
                updated_at: '2025-12-08T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Update Stock',
                description: 'Add, subtract or set stock quantity',
                url: '/api/products/1/stock',
                method: 'PUT',
                request: { operation: 'add', quantity: 50, notes: 'New shipment' },
                response: {
                    status: true,
                    message: 'Stock updated successfully',
                    data: { id: 1, stock_quantity: 150 }
                }
            }
        ]
    },
    {
        path: '/:id/stock/movements',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getStockMovements(req, res),
        description: 'Get stock movement history for a product',
        database: {
            tables: ['stock_movements', 'products'],
            mainTable: 'stock_movements',
            fields: {
                stock_movements: ['id', 'product_id', 'movement_type', 'quantity', 'reference_type', 'reference_id', 'notes', 'created_by', 'created_at']
            },
            relationships: ['stock_movements.product_id -> products.id (FK)']
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Stock movements retrieved successfully',
            pagination: {
                total: 15,
                page: '1',
                limit: '10',
                totalPage: 2,
                product: {
                    id: 1,
                    name: 'Wireless Mouse',
                    sku: 'MOU-001',
                    current_stock: 150,
                    initial_stock: 100
                }
            },
            data: [
                {
                    id: 1,
                    product_id: 1,
                    movement_type: 'sale',
                    quantity: -2,
                    reference_type: 'order',
                    reference_id: 1,
                    notes: 'Stock deducted for order ORD-1733130000000-123',
                    created_by: 1,
                    created_at: '2025-12-08T10:00:00.000Z'
                },
                {
                    id: 2,
                    product_id: 1,
                    movement_type: 'purchase',
                    quantity: 100,
                    reference_type: 'manual_adjustment',
                    reference_id: null,
                    notes: 'Stock add operation',
                    created_by: 1,
                    created_at: '2025-12-08T09:00:00.000Z'
                }
            ]
        },
        examples: [
            {
                title: 'Get Stock Movements',
                description: 'Retrieve stock history for a product',
                url: '/api/products/1/stock/movements',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Stock movements retrieved successfully',
                    data: [{ id: 1, movement_type: 'sale', quantity: -2 }]
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => productsController.deleteProduct(req, res),
        description: 'Delete a product',
        database: {
            tables: ['products', 'stock_movements', 'product_images'],
            mainTable: 'products',
            sideEffects: ['Deletes associated product_images', 'Prevents deletion if stock_movements exist (usually)']
        },
        sampleResponse: {
            status: true,
            message: 'Product deleted successfully'
        },
        examples: [
            {
                title: 'Delete Product',
                description: 'Delete a product from inventory',
                url: '/api/products/5',
                method: 'DELETE',
                response: {
                    status: true,
                    message: 'Product deleted successfully'
                }
            }
        ]
    },

    // Product Image Gallery routes





    // Category CRUD routes
    {
        path: '/categories',
        method: 'POST',
        middlewares: [validate(createCategory)],
        handler: handlerWithFields((req, res) => productsController.createCategory(req, res), createCategory),
        description: 'Create a new category',
        database: {
            tables: ['categories'],
            mainTable: 'categories',
            requiredFields: ['name'],
            optionalFields: ['description', 'parent_id', 'is_active'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at'],
            relationships: ['categories.parent_id -> categories.id (self-referencing)']
        },
        sampleRequest: {
            name: 'Furniture',
            description: 'Office and home furniture',
            parent_id: null,
            is_active: true
        },
        sampleResponse: {
            status: true,
            message: 'Category created successfully',
            data: {
                id: 3,
                name: 'Furniture',
                created_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Create Category',
                description: 'Add a new product category',
                url: '/api/products/categories',
                method: 'POST',
                request: { name: 'Furniture', description: 'Office furniture' },
                response: {
                    status: true,
                    message: 'Category created successfully',
                    data: { id: 3, name: 'Furniture' }
                }
            }
        ]
    },
    {
        path: '/categories/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getCategoryById(req, res),
        description: 'Get a specific category by ID',
        database: {
            tables: ['categories'],
            mainTable: 'categories',
            fields: {
                categories: ['id', 'name', 'description', 'parent_id', 'is_active', 'created_at', 'updated_at']
            },
            relationships: ['categories.parent_id -> categories.id (self-referencing)']
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                name: 'Electronics',
                description: 'Electronic devices and accessories',
                parent_id: null,
                is_active: true
            }
        },
        examples: [
            {
                title: 'Get Category',
                description: 'Get category details by ID',
                url: '/api/products/categories/1',
                method: 'GET',
                response: {
                    status: true,
                    data: { id: 1, name: 'Electronics' }
                }
            }
        ]
    },
    {
        path: '/categories/:id',
        method: 'PUT',
        middlewares: [validate(updateCategory)],
        handler: handlerWithFields((req, res) => productsController.updateCategory(req, res), updateCategory),
        description: 'Update a category',
        database: {
            tables: ['categories'],
            mainTable: 'categories',
            updatableFields: ['name', 'description', 'parent_id', 'is_active'],
            readOnlyFields: ['id', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            name: 'Electronics & Gadgets',
            description: 'Updated description',
            is_active: true
        },
        sampleResponse: {
            status: true,
            message: 'Category updated successfully',
            data: {
                id: 1,
                name: 'Electronics & Gadgets',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Update Category',
                description: 'Update existing category',
                url: '/api/products/categories/1',
                method: 'PUT',
                request: { name: 'Electronics & Gadgets' },
                response: {
                    status: true,
                    message: 'Category updated successfully'
                }
            }
        ]
    },
    {
        path: '/categories/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => productsController.deleteCategory(req, res),
        description: 'Delete a category',
        database: {
            tables: ['categories', 'products'],
            mainTable: 'categories',
            sideEffects: ['Check for associated products before deletion']
        },
        sampleResponse: {
            status: true,
            message: 'Category deleted successfully'
        },
        examples: [
            {
                title: 'Delete Category',
                description: 'Remove a category',
                url: '/api/products/categories/3',
                method: 'DELETE',
                response: {
                    status: true,
                    message: 'Category deleted successfully'
                }
            }
        ]
    },
    // Unit CRUD routes
    {
        path: '/units',
        method: 'POST',
        middlewares: [validate(createUnit)],
        handler: handlerWithFields((req, res) => productsController.createUnit(req, res), createUnit),
        description: 'Create a new unit',
        database: {
            tables: ['units'],
            mainTable: 'units',
            requiredFields: ['name', 'symbol'],
            optionalFields: ['description', 'is_active'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            name: 'Dozen',
            symbol: 'dz',
            is_active: true
        },
        sampleResponse: {
            status: true,
            message: 'Unit created successfully',
            data: {
                id: 6,
                name: 'Dozen',
                symbol: 'dz',
                created_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Create Unit',
                description: 'Add a new measurement unit',
                url: '/api/products/units',
                method: 'POST',
                request: { name: 'Dozen', symbol: 'dz' },
                response: {
                    status: true,
                    message: 'Unit created successfully',
                    data: { id: 6, name: 'Dozen', symbol: 'dz' }
                }
            }
        ]
    },
    {
        path: '/units/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => productsController.getUnitById(req, res),
        description: 'Get a specific unit by ID',
        database: {
            tables: ['units'],
            mainTable: 'units',
            fields: {
                units: ['id', 'name', 'symbol', 'is_active', 'created_at', 'updated_at']
            }
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                name: 'Piece',
                symbol: 'pcs',
                is_active: true
            }
        },
        examples: [
            {
                title: 'Get Unit',
                description: 'Get unit details by ID',
                url: '/api/products/units/1',
                method: 'GET',
                response: {
                    status: true,
                    data: { id: 1, name: 'Piece', symbol: 'pcs' }
                }
            }
        ]
    },
    {
        path: '/units/:id',
        method: 'PUT',
        middlewares: [validate(updateUnit)],
        handler: handlerWithFields((req, res) => productsController.updateUnit(req, res), updateUnit),
        description: 'Update a unit',
        database: {
            tables: ['units'],
            mainTable: 'units',
            updatableFields: ['name', 'symbol', 'is_active'],
            readOnlyFields: ['id', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            name: 'Pieces',
            symbol: 'pcs',
            is_active: true
        },
        sampleResponse: {
            status: true,
            message: 'Unit updated successfully',
            data: {
                id: 1,
                name: 'Pieces',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Update Unit',
                description: 'Update existing unit',
                url: '/api/products/units/1',
                method: 'PUT',
                request: { name: 'Pieces' },
                response: {
                    status: true,
                    message: 'Unit updated successfully',
                    data: { id: 1, name: 'Pieces' }
                }
            }
        ]
    },
    {
        path: '/units/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => productsController.deleteUnit(req, res),
        description: 'Delete a unit',
        database: {
            tables: ['units', 'products'],
            mainTable: 'units',
            sideEffects: ['Check for associated products before deletion']
        },
        sampleResponse: {
            status: true,
            message: 'Unit deleted successfully'
        },
        examples: [
            {
                title: 'Delete Unit',
                description: 'Remove a unit',
                url: '/api/products/units/6',
                method: 'DELETE',
                response: {
                    status: true,
                    message: 'Unit deleted successfully'
                }
            }
        ]
    }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
