const express = require('express');
const router = express.Router();
const leaveController = require('./leaves.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createLeave, updateLeave, updateStatus } = require('./leaves.validation');

// Module name for routes-tree grouping
router.moduleName = 'Leave Management';

router.use(verifyToken);
router.use(moduleCheck('leaves'));

// Define routes metadata
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => leaveController.getLeaves(req, res),
        description: 'List leave applications',
        database: {
            tables: ['leaves', 'staffs'],
            mainTable: 'leaves',
            fields: {
                leaves: ['id', 'staff_id', 'leave_type', 'start_date', 'end_date', 'reason', 'status', 'approved_by', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name']
            },
            relationships: ['leaves.staff_id -> staffs.id (FK)', 'leaves.approved_by -> staffs.id (FK)']
        },
        queryParams: {
            staff_id: 'Filter by staff ID',
            status: 'Filter by status',
            leave_type: 'Filter by leave type',
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)'
        },
        sampleResponse: {
            success: true,
            message: 'Leave applications retrieved successfully',
            pagination: {
                total: 50,
                page: '1',
                limit: '10',
                totalPage: 5
            },
            data: [
                {
                    id: 1,
                    staff_id: 5,
                    leave_type: 'annual',
                    start_date: '2025-12-25',
                    end_date: '2025-12-31',
                    status: 'approved'
                }
            ]
        }
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [validate(createLeave)],
        handler: handlerWithFields((req, res) => leaveController.createLeave(req, res), createLeave),
        description: 'Apply for leave',
        database: {
            tables: ['leaves'],
            mainTable: 'leaves',
            requiredFields: ['staff_id', 'leave_type', 'start_date', 'end_date'],
            optionalFields: ['reason'],
            autoGeneratedFields: ['id', 'status', 'created_at', 'updated_at']
        },
        sampleRequest: {
            staff_id: 5,
            leave_type: 'sick',
            start_date: '2025-12-02',
            end_date: '2025-12-03',
            reason: 'Fever'
        },
        sampleResponse: {
            status: true,
            message: 'Leave application submitted successfully'
        }
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => leaveController.getLeaveById(req, res),
        description: 'Get leave application details',
        database: {
            tables: ['leaves', 'staffs'],
            mainTable: 'leaves',
            fields: {
                leaves: ['id', 'staff_id', 'leave_type', 'start_date', 'end_date', 'reason', 'status', 'approved_by', 'created_at', 'updated_at'],
                staffs: ['id', 'first_name', 'last_name']
            },
            relationships: ['leaves.staff_id -> staffs.id (FK)', 'leaves.approved_by -> staffs.id (FK)']
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                leave_type: 'sick',
                status: 'pending'
            }
        }
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updateLeave)],
        handler: handlerWithFields((req, res) => leaveController.updateLeave(req, res), updateLeave),
        description: 'Update leave application',
        database: {
            tables: ['leaves'],
            mainTable: 'leaves',
            updatableFields: ['leave_type', 'start_date', 'end_date', 'reason'],
            readOnlyFields: ['id', 'staff_id', 'status', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            reason: 'High Fever'
        },
        sampleResponse: {
            status: true,
            message: 'Leave application updated successfully'
        }
    },
    {
        path: '/:id/status',
        method: 'PUT',
        middlewares: [validate(updateStatus)],
        handler: handlerWithFields((req, res) => leaveController.updateStatus(req, res), updateStatus),
        description: 'Approve or Reject leave',
        database: {
            tables: ['leaves'],
            mainTable: 'leaves',
            updatableFields: ['status', 'approved_by'],
            sideEffects: ['Sets approved_by to current user ID', 'Updates status to approved/rejected']
        },
        sampleRequest: {
            status: 'approved'
        },
        sampleResponse: {
            status: true,
            message: 'Leave application approved successfully'
        }
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => leaveController.deleteLeave(req, res),
        description: 'Delete leave application',
        database: {
            tables: ['leaves'],
            mainTable: 'leaves'
        },
        sampleResponse: {
            status: true,
            message: 'Leave application deleted successfully'
        }
    }
];

// Register routes
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
