const express = require('express');
const router = express.Router();
const customersController = require('./customers.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createCustomer, updateCustomer } = require('./customers.validation');

// Module name for routes-tree grouping
router.moduleName = 'Customers';

router.use(verifyToken);
router.use(moduleCheck('customers'));

// Define routes metadata with comprehensive documentation
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => customersController.getAllCustomers(req, res),
        description: 'Get all customers with pagination',
        database: {
            tables: ['customers'],
            mainTable: 'customers',
            fields: {
                customers: ['id', 'name', 'email', 'phone', 'company', 'address', 'city', 'state', 'country', 'postal_code', 'tax_id', 'credit_limit', 'payment_terms', 'notes', 'is_active', 'created_at', 'updated_at']
            }
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)',
            customer_type: 'Filter by customer type (individual/business)',
            is_active: 'Filter by active status (true/false)',
            search: 'Search by name, email, phone, or company'
        },
        sampleResponse: {
            success: true,
            message: 'Customers retrieved successfully',
            pagination: {
                total: 5,
                page: '1',
                limit: '10',
                totalPage: 1
            },
            data: [
                {
                    id: 1,
                    tax_id: 'TAX123456',
                    credit_limit: 10000.00,
                    outstanding_balance: 2500.00,
                    customer_type: 'business',
                    is_active: true,
                    created_at: '2025-12-02T10:00:00.000Z'
                }
            ]
        },
        examples: [
            {
                title: 'List Customers',
                description: 'Get paginated list of customers with optional filtering',
                url: '/api/customers?page=1&limit=10&customer_type=business',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Customers retrieved successfully',
                    pagination: { total: 5, page: '1', limit: '10', totalPage: 1 },
                    data: [{ id: 1, name: 'John Doe', customer_type: 'business', is_active: true }]
                }
            }
        ]
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [validate(createCustomer)],
        handler: handlerWithFields((req, res) => customersController.createCustomer(req, res), createCustomer),
        description: 'Add a new customer',
        database: {
            tables: ['customers'],
            mainTable: 'customers',
            requiredFields: ['name'],
            optionalFields: ['email', 'phone', 'company', 'address', 'city', 'state', 'country', 'postal_code', 'tax_id', 'credit_limit', 'payment_terms', 'notes', 'is_active'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            name: 'Jane Smith',
            email: 'jane.smith@example.com',
            phone: '+1987654321',
            company: 'Tech Solutions Inc',
            address: '456 Business Ave',
            city: 'San Francisco',
            state: 'CA',
            country: 'USA',
            postal_code: '94102',
            latitude: 37.7749,
            longitude: -122.4194,
            tax_id: 'TAX789012',
            credit_limit: 15000.00,
            customer_type: 'business',
            notes: 'Premium customer',
            is_active: true
        },
        sampleResponse: {
            status: true,
            message: 'Customer created successfully',
            data: {
                id: 2,
                name: 'Jane Smith',
                email: 'jane.smith@example.com',
                created_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Create Customer',
                description: 'Add a new customer to the database',
                url: '/api/customers',
                method: 'POST',
                request: {
                    name: 'Jane Smith',
                    email: 'jane.smith@example.com',
                    phone: '+1987654321',
                    company: 'Tech Solutions Inc',
                    address: '456 Business Ave',
                    city: 'San Francisco',
                    state: 'CA',
                    country: 'USA',
                    postal_code: '94102',
                    tax_id: 'TAX789012',
                    credit_limit: 15000.00,
                    customer_type: 'business',
                    is_active: true
                },
                response: {
                    status: true,
                    message: 'Customer created successfully',
                    data: { id: 2, name: 'Jane Smith', email: 'jane.smith@example.com' }
                }
            }
        ]
    },
    {
        path: '/maps',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => customersController.getCustomerLocations(req, res),
        description: 'List of customer locations for map display',
        database: {
            tables: ['customers'],
            mainTable: 'customers',
            fields: {
                customers: ['id', 'name', 'company', 'address', 'city', 'phone', 'email', 'latitude', 'longitude']
            }
        },
        sampleResponse: {
            status: true,
            data: {
                total: 25,
                locations: [
                    {
                        id: 1,
                        name: 'John Doe',
                        company: 'Acme Corp',
                        address: '123 Main Street',
                        city: 'New York',
                        phone: '+1234567890',
                        email: 'john.doe@example.com',
                        coordinates: {
                            lat: 40.7128,
                            lng: -74.0060
                        }
                    },
                    {
                        id: 2,
                        name: 'Jane Smith',
                        company: 'Tech Solutions Inc',
                        address: '456 Business Ave',
                        city: 'San Francisco',
                        phone: '+1987654321',
                        email: 'jane.smith@example.com',
                        coordinates: {
                            lat: 37.7749,
                            lng: -122.4194
                        }
                    }
                ]
            }
        },
        examples: [
            {
                title: 'Get Customer Locations',
                description: 'Get list of customers with geolocation data',
                url: '/api/customers/maps',
                method: 'GET',
                response: {
                    status: true,
                    data: {
                        total: 25,
                        locations: [{ id: 1, name: 'John Doe', coordinates: { lat: 40.7128, lng: -74.0060 } }]
                    }
                }
            }
        ]
    },
    {
        path: '/stats',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => customersController.getCustomerStats(req, res),
        description: 'Get customer statistics (Active, Total, Revenue, New)',
        database: {
            tables: ['customers', 'orders'],
            mainTable: 'customers',
            fields: {
                calculated: ['activeCustomers', 'totalCustomers', 'totalRevenue', 'newCustomers']
            }
        },
        sampleResponse: {
            status: true,
            message: 'Customer stats retrieved successfully',
            data: [
                {
                    label: "Active Customers",
                    value: 123,
                    color: "bg-green-600"
                }
            ]
        },
        examples: [
            {
                title: 'Get Customer Stats',
                description: 'Get statistical overview of customer data',
                url: '/api/customers/stats',
                method: 'GET',
                response: {
                    status: true,
                    message: 'Customer stats retrieved successfully',
                    data: [{ label: "Active Customers", value: 123 }]
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => customersController.getCustomerById(req, res),
        description: 'Get customer details',
        database: {
            tables: ['customers'],
            mainTable: 'customers',
            fields: {
                customers: ['id', 'name', 'email', 'phone', 'company', 'address', 'city', 'state', 'country', 'postal_code', 'tax_id', 'credit_limit', 'payment_terms', 'notes', 'is_active', 'created_at', 'updated_at']
            }
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                name: 'John Doe',
                email: 'john.doe@example.com',
                phone: '+1234567890',
                company: 'Acme Corp',
                address: '123 Main Street',
                city: 'New York',
                state: 'NY',
                country: 'USA',
                postal_code: '10001',
                latitude: 40.7128,
                longitude: -74.0060,
                tax_id: 'TAX123456',
                credit_limit: 10000.00,
                outstanding_balance: 2500.00,
                customer_type: 'business',
                notes: 'Long-term customer',
                is_active: true,
                created_at: '2025-12-02T10:00:00.000Z',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Get Customer',
                description: 'Get customer details by ID',
                url: '/api/customers/1',
                method: 'GET',
                response: {
                    status: true,
                    data: { id: 1, name: 'John Doe', email: 'john.doe@example.com' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updateCustomer)],
        handler: handlerWithFields((req, res) => customersController.updateCustomer(req, res), updateCustomer),
        description: 'Update a customer',
        database: {
            tables: ['customers'],
            mainTable: 'customers',
            updatableFields: ['name', 'email', 'phone', 'company', 'address', 'city', 'state', 'country', 'postal_code', 'tax_id', 'credit_limit', 'payment_terms', 'notes', 'is_active'],
            readOnlyFields: ['id', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            name: 'John Doe Jr.',
            phone: '+1234567899',
            credit_limit: 12000.00,
            notes: 'Updated credit limit'
        },
        sampleResponse: {
            status: true,
            message: 'Customer updated successfully',
            data: {
                id: 1,
                name: 'John Doe Jr.',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Update Customer',
                description: 'Update existing customer details',
                url: '/api/customers/1',
                method: 'PUT',
                request: { name: 'John Doe Jr.', credit_limit: 12000.00 },
                response: {
                    status: true,
                    message: 'Customer updated successfully',
                    data: { id: 1, name: 'John Doe Jr.' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => customersController.deleteCustomer(req, res),
        description: 'Delete a customer',
        database: {
            tables: ['customers', 'orders'],
            mainTable: 'customers',
            sideEffects: ['May affect existing orders - check foreign key constraints']
        },
        sampleResponse: {
            status: true,
            message: 'Customer deleted successfully'
        },
        examples: [
            {
                title: 'Delete Customer',
                description: 'Remove a customer',
                url: '/api/customers/1',
                method: 'DELETE',
                response: {
                    status: true,
                    message: 'Customer deleted successfully'
                }
            }
        ]
    }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
